### ISSUE TITLE
Don't move wormholes into examples (i.e. move it back)

### ISSUE THREAD

**Issue by turion** [ivanperez-keera/dunai#100]
This has a practical and a philosophical reason.

* Practical: If it's in examples, it's not in the main library and can't be imported. (Or nearly as bad, if it's a separate package, it's a separate dependency, for just a single functionality.) Dunai doesn't really work multithreaded without wormholes, so I really suggest putting them in the main library. (E.g. rhine would depend on them.)
* Philosophical: Wormholes are a research result, not an FRP library. In particular, there is no API we are matching with the code from `Data.MonadicStreamFunction.Wormhole`.

I think Daniel Winograd-Cort has no working implementation of wormholes. If he does, all the better, then I'm happy to write a file that reproduces his API exactly and uses our wormholes under the hood.

**Comment by turion** [comment]
Congratulations to myself on the 100th issue ;)

**Comment by ivanperez-keera** [comment]
For now: can you import it from examples as a library, or temporarily add it to rhine with a pending issue of deciding where it should be?

**Comment by ivanperez-keera** [comment]
For now, this is not going to happen. Further down the line, we can re-evaluate it.
