### ISSUE TITLE
Put dunai and bearriver on stackage

### ISSUE THREAD

**Issue by turion** [ivanperez-keera/dunai#101]
* Instructions are here: https://github.com/fpco/stackage/blob/master/MAINTAINERS.md#adding-a-package
* I can be stackage maintainer for dunai.

Which other packages should go on stackage? `bearriver`?

**Comment by ivanperez-keera** [comment]
I'm not sure anything *should* (or *shouldn't*) be on stackage.

I wouldn't push to add anything until the API is stable, but you are more than free to submit it if you want, especially if it's a dependency to something else you are adding.

**Comment by ivanperez-keera** [comment]
(If anything needs to be added to dunai, just submit a PR.)

**Comment by ivanperez-keera** [comment]
Please, submit PRs.

https://github.com/ivanperez-keera/dunai/commit/3bcbcdb1c1f0493f24dc2ba671e70ffb49759b21

**Comment by turion** [comment]
This is now: https://github.com/fpco/stackage/pull/3603

Just for info: I'm adding dunai as a dependency for `rhine` and its subsidiary packages.

**Comment by turion** [comment]
This is closed as per https://github.com/fpco/stackage/pull/3603
