### ISSUE TITLE
list-t does not build with GHC 7.6.3

### ISSUE THREAD

**Issue by ivanperez-keera** [ivanperez-keera/dunai#103]
Reported by @turion in #102 .

list-t doesn't build with GHC 7.6.3 (see this failed job) since some module it needs wasn't ported to the corresponding old version of base. Since that's none of our business, it seems best to just exclude it from the build matrix.

When reordering the exclude points, I might have fixed an issue that excluded all GHC 8.2.1 builds and all keerahails builds (I think we want to exclude only the combination of 8.2.1 and keerahails).

**Comment by turion** [comment]
What about this now? Shall I submit a new PR?
