### ISSUE TITLE
Reimplement fifo in terms of sequences

### ISSUE THREAD

**Issue by turion** [ivanperez-keera/dunai#105]
https://github.com/ivanperez-keera/dunai/blob/3bcbcdb1c1f0493f24dc2ba671e70ffb49759b21/src/Data/MonadicStreamFunction/Util.hs#L95

Concatenation of sequences is much faster than concatenation of lists.

**Comment by ivanperez-keera** [comment]
I'm summarily delaying all performance-related issues until we have the right framework to do this right. As I said in a different comment, we have an intern coming to study how to do this generally for FRP frameworks, and dunai and Yampa should benefit from that.

That may give us a more systematic way of approaching all performance limitations and improvements.
