### ISSUE TITLE
Erratas in the article: Functional Reactive Programming, Refactored (Haskell Symposium 2016)

### ISSUE THREAD

**Issue by chriz-keera** [ivanperez-keera/dunai#106]
Hi,

while I was reading parts of this article:

Functional Reactive Programming, Refactored
Haskell 2016 Proceedings of the 9th International Symposium on Haskell
Pages 33-44

I found two points that confused me and I think that there is something wrong with it:

In Section 4.1 Reader

There is a parenthesis mismatch in 
```
  embed (    runReaderS testMSF (GameSettings 0 3)
         &&& runReaderS testMSF (GameSettings 0 2))
        (repeat 5 ()))
```
I guess it should be:
```
  embed (    runReaderS testMSF (GameSettings 0 3)
         &&& runReaderS testMSF (GameSettings 0 2)
        )
        (
         repeat 5 ()
        )
```
The result of this function is stated as:

```
[ ((1, False), (1, False)), ((2, False), (2, False))
, ((3, False), (3, True )), ((4, True ), (4, True ))
, ((5, True ), (5, True ))]
```
but I think it should be `((2, False), (2, True))`:

```
[ ((1, False), (1, False)), ((2, False), (2, True ))
, ((3, False), (3, True )), ((4, True ), (4, True ))
, ((5, True ), (5, True ))]
```

I hope this is the right place to mention these issues.

Best,
Christina

**Comment by ivanperez-keera** [comment]
This is true, and it should probably be listed officially somewhere. I link to the article on my website, so there could be a link to an errata there. @turion do you have the article listed on your website or something?

**Comment by turion** [comment]
True. I'll link to this issue for errata for the time being.

**Comment by ivanperez-keera** [comment]
Acknowledged. I'm linking to the paper from my website.
