### ISSUE TITLE
Time leak in exceptions

### ISSUE THREAD

**Issue by turion** [ivanperez-keera/dunai#108]
It seems to me that exceptions can create a time leak. Consider the following example

```haskell
cycleS :: Monad m => [a] -> MSF m arbitrary a
cycleS = safely . forever . try . maybeToExceptS . listToMaybeS
```
This creates an `MSF` that cycles through the values of the given list. But if the list is short and we cycle through it endlessly, this becomes slower and slower. I don't understand why.

By the way, it's no problem to create a version of this that doesn't have the problem:
```haskell
cycleS :: Monad m => NonEmpty a -> MSF m () a
cycleS as = unfold (second (fromMaybe as) . uncons) as
```
But it's imaginable that there are situations where we need to handle a constant, high rate of exceptions, and in such situations the program would be slowed down arbitrarily.

What's the reason for this slowdown?

**Comment by ivanperez-keera** [comment]
Performance can be tricky. I don't immediately have the time to look into this.

We have an intern coming to look into performance and FRP, with Yampa and dunai as practical use cases, so that may give us hints about when these things are happening, although not necessarily the reasons behind that.

If you do find out, please, reply.

**Comment by turion** [comment]
I believe this could be related to #169. Reopening temporarily for triage. Also note that `listToMaybeS` was broken some time after I reported this issue here.

**Comment by ivanperez-keera** [comment]
For info: in the end, the intern did not come.

**Comment by turion** [comment]
Possibly fixing #170 will fix this here. I'm investigating.

**Comment by turion** [comment]
No, #170 is unrelated.

**Comment by turion** [comment]
In fact, I cannot reproduce this anymore. Possibly, newer GHCs can optimize something away that older GHCs couldn't?

**Comment by turion** [comment]
This can be reproduced for example by running `reactimate $ arrM (const getCurrentTime) >>> (arr id &&& cycleS [1..10]) >>> arrM (\(t, _) -> getCurrentTime >>= (\t' -> print (diffUTCTime t' t)))`

**Comment by turion** [comment]
Replacing `data` by `newtype` in the definition of `MSF` (#169) does not alleviate this issue. I'm out of ideas again. Closing since I have no idea what to do.

**Comment by ivanperez-keera** [comment]
I hope that we will be able to benchmark dunai well in two or three major milestones. When we do, we can review this more carefully.
