### ISSUE TITLE
Conflicting family instance declarations

### ISSUE THREAD

**Issue by tmh2211** [ivanperez-keera/dunai#11]
When I make my own Vector type an instance of RModule and then want to use an operator cabal gives the following error message:
`Conflicting family instance declarations:`
      `Data.VectorSpace.Groundring a`
       ` -- Defined in Data.VectorSpace.Instances'`
      `Data.VectorSpace.Groundring Vector`
      `  -- Defined in Robotics.ArDrone.NavDataTypes'`

**Comment by turion** [comment]
Fixed on develop_haskell_symposium with 67af9b1ae4d2f89dc2eb56041b5a6d442caed56f.

**Comment by turion** [comment]
There was an issue with module names, this is fixed now in ad60b53.
