### ISSUE TITLE
arrM_ missing?

### ISSUE THREAD

**Issue by thalerjonathan** [ivanperez-keera/dunai#127]
It seems that arrM_ has disappeared in 0.5.1. I understand that its quite easy to get the functionality by simply:
```
arrM_ :: Monad m => m b -> MSF m a b
arrM_ f = arrM (const f)
```
Why not leave it in / bring it back?

**Comment by thalerjonathan** [comment]
Sorry... I just realised constM is what I need...

**Comment by turion** [comment]
Also note https://github.com/ivanperez-keera/dunai/issues/99
