### ISSUE TITLE
GSoC: Any plan to participate in GSoC?

### ISSUE THREAD

**Issue by Rizary** [ivanperez-keera/dunai#129]
Hi,

As you may notice in the mailing list recently, there is upcoming GSoC for Haskell.org. 

For more information, you can take a look here to upload the idea: https://github.com/haskell-org/summer-of-haskell

The official website is https://summer.haskell.org/

If there is a project idea to participate this summer, maybe we can submit the idea along with who gonna be a mentor.

**Comment by ivanperez-keera** [comment]
Thank you. Do you have a specific idea in mind?

**Comment by turion** [comment]
A few things that come to my mind:

* Entry for the frp-zoo
* Reverse frp-zoo
* An bigger real-life example application (game? webserver?) that uses all important monads (`ExceptT`, `StateT`, `ReaderT`, maybe `ListT`, ...) in a sensible way

**Comment by turion** [comment]
I thought about porting https://wiki.haskell.org/Frag to Rhine, which would be a stress-test for both Rhine and Dunai.

**Comment by Rizary** [comment]
@ivanperez-keera 

I have not used Arrowized FRP extensively at the moment. I have used another FRP (like Reflex) for building some of my web app projects and from my experience (as a mentor last year), the projects that were selected by Haskell organization is the one that can benefit the community in general. For me, Arrowized FRP is one of them.

**Comment by turion** [comment]
I think we should really enter with a reverse FRP zoo. That would be a big benefit for the community, because we can actually fulfill our promise that most FRP frameworks can be emulated by Dunai.

**Comment by ivanperez-keera** [comment]
I welcome people doing more and more stuff related to Dunai.

That being said, when I tried to start a reverse FRP zoo with just one (non trivial) FRP implementation for a paper, it took forever. So this task is much bigger than it seems.

I definitely do not have the time to supervise that kind of work, or be responsible for it.

**Comment by turion** [comment]
> So this task is much bigger than it seems.

That's valuable advice. Maybe it would be enough to create one classical framework for the reverse zoo, e.g. reactive-banana, or fran. Other classical frameworks wouldn't be so much different and can be left out.

I imagine I could find time to supervise such a project. But to be honest I have no idea how much time that would cost.

**Comment by turion** [comment]
> when I tried to start a reverse FRP zoo with just one (non trivial) FRP implementation for a paper

I imagine you mean bearriver? Or something else I'm not aware of?

**Comment by turion** [comment]
Would that collide with my proposal of one classical framework?

**Comment by ajatdarojat45** [comment]
Mas saya mau coba ikut Google summer of code, apa saja yang perlu di siapin?

**Comment by ivanperez-keera** [comment]
@ajatdarojat45 What particular idea would you like to work on?

**Comment by ivanperez-keera** [comment]
Regarding the potential of creating a tutorial, this may be relevant (ICFP2019 PC members, please wait until past April 16 to open: https://bit.ly/2Uw1maY).

**Comment by Rizary** [comment]
@ajatdarojat45 please use English so anyone here can help you.

GSoC Application already closed. These are what you can do:
1. Learning dunai, or in general about Arrowized FRP
2. Pick one idea that would benefit haskell community in the area of FRP
