### ISSUE TITLE
Distributed Systems Extensions for Dunai

### ISSUE THREAD

**Issue by jgotoh** [ivanperez-keera/dunai#137]
Hi there!

I recently started working on the final thesis of my studies. The goal of the thesis is to demonstrate the usage of FRP in distributed systems (e.g multiplayer games).

To do this, I want to create a library extending Dunai. 
The library should help developers create distributed simulations by delivering algorithms to synchronise simulations across a network and support different architectures like Client/ Server and Peer-To-Peer.

For all things related to networking I want to use and extend [Cloud Haskell](https://haskell-distributed.github.io/).

So my question to you is: what features would you like to see in such a library?

Here is a rough draft of the features I currently plan to implement:

- Handling of connections (discovering, connecting, disconnecting)
- Support for different architectures (Client/ Server, variants of Peer-To-Peer)
- Synchronisation
  - Conservative (like Lamport-Clocks)
  - Optimistic
- Using the type system to notify when error-handling is necessary (analogous to the Fault Tolerant FRP paper)
- Means to test distributed simulations

Are there any additional features you can think of? I'd be glad to get new ideas and inspirations.

Currently I am exploring the usage of Dunai and the basics of network communication, but I plan to release my work in a public repository once I have implemented some first features.

Thank you very much!

Cheers,

Julian

**Comment by turion** [comment]
A few ideas:

* Extend/fork `dunai` to include graded monads (https://hackage.haskell.org/package/effect-monad) or something like that to safely handle connection sockets/sessions.
* Connect to https://github.com/turion/rhine in matters of synchronisation and clocks
* For error handling, use https://github.com/ivanperez-keera/dunai/blob/develop/src/Control/Monad/Trans/MSF/Except.hs

**Comment by ivanperez-keera** [comment]
I think that's a good list, and I'd be very happy to see that completed.

The use of handles or sockets introduces a new requirement: some elements needed for an MSF only exist so long as a given resource exists. I believe this may have a connection with Continuation monads, something I've always wanted to explore more in connection with Dunai and I think is very promising. Perhaps your work will shed some light on this connection, if it exists.

I agree on the possible connection with graded monads, but do not despair if it seems "too hard" to achieve within your timeline. It would be really hard for me too.

In an SMCIT paper (which I can send you by email), and a new JFP submission, testing and fault tolerance were used to verify satellite communications and distributed consensus. I'll send this asap.

**Comment by ivanperez-keera** [comment]
And one little thought to keep in mind, and I don't expect anyone to be able to solve this soon: in games, when played distributed, there's some lag that needs to be resolved. This is yet another version of the problem of distributed consensus.

I saw some work at ICFP 2017 on this, but it would be nice to see a solution expressed in terms of signals, time, and FRP.

**Comment by turion** [comment]
Here is a bigger idea that I never brought to paper. You're welcome to add it or be inspired by it. It might be useful in the context of concurrency and distributed systems. I'd call it "effect wormholes" after @dwincort's wormholes (implemented for `dunai` in https://github.com/ivanperez-keera/dunai/blob/ccf34e2857d2d4030b15682e03cf0d432896c8e5/examples/reversefrpzoo/wormholes/src/Data/MonadicStreamFunction/Wormhole.hs).

Sometimes we have a couple `MSF` that we'd want to execute concurrently, but we'd like to synchronise some of their effects.

For example, if we have two `MSF (ReaderT r IO) () ()`, we can put those in separate threads and pass them the same environment `r` upon forking:

```
forkMSF :: MSF IO () () -> IO ()
forkMSF = void . forkIO . reactimate

launchTwoReaders :: MSF (ReaderT r IO) () () -> MSF (ReaderT r IO) () () -> ReaderT r IO ()
launchTwoReaders msf1 msf2 = ReaderT $ \r -> do
  forkMSF $ runReaderS_ msf1 r
  forkMSF $ runReaderS_ msf2 r
```

 Or if we have `MSF (WriterT w IO) () ()`, we can collect the writer effect in a joint `IORef`:

```
captureLogConcurrently :: MSF (WriterT w IO) () () -> IO (MSF (WriterT w IO () ())
captureLogConcurrently msf = do
  ref <- newIORef mempty
  forkMSF $ runWriterS msf >>> arrM (\((), w) -> modifyIORef ref (mappend w))
  constM $ readIORef ref
```

This kind of thing is more intricate for `StateT` and `ExceptT`. (But probably still doable.) There is a general pattern to this. We have some additional effect, and we want to execute & locally reestablish/synchronise it across a concurrent system. I think a general pattern would be an "effect wormhole:

```
data EffectWormhole m1 m2 = EffectWormhole
  { up :: forall a . m1 a -> m2 a
  , down :: forall a . m2 a -> m1 a
  }
```
For example, the `WriterT` example would use something of type `Monoid w => IO (EffectWormhole (WriterT w IO) IO)`.

It would be interesting to work this out and see whether it's as useful as normal wormholes.

**Comment by ivanperez-keera** [comment]
I'm not sure we helped in any way. @boggledekoog please let us know if you have any questions, or if we led you too far of.

(Shoot me an email if you prefer.)

**Comment by ivanperez-keera** [comment]
@turion "Extend/fork dunai to include graded monads (https://hackage.haskell.org/package/effect-monad) or something like that to safely handle connection sockets/sessions."

If this is similar to indexed monads: could you reconstruct it from my "Fault Tolerant FRP" paper?

**Comment by turion** [comment]
@ivanperez-keera
> If this is similar to indexed monads: could you reconstruct it from my "Fault Tolerant FRP" paper?
 Yes, that should be possible! Thanks for the pointer, I had forgotten that your paper has that.

**Comment by jwaldmann** [comment]
> when played distributed, there's some lag that needs to be resolved.

I just found this (somewhat long-winded, non-formal) explanation of how this is 
handled in some games: https://arstechnica.com/gaming/2019/10/explaining-how-fighting-games-use-delay-based-and-rollback-netcode/

**Comment by RiugaBachi** [comment]
@jwaldmann ...Which is precisely why the notion of FRP is so fitting for MMO server development. @boggledekoog I've had a very similar (perhaps slightly more nuanced?) idea in mind for the past several months but never got past the theorizing stage. In any case, both of our ideas involve FRP and Cloud Haskell. I would most certainly be interested in any future discussions and/or collaboration. I've used FRP in several server emulator designs for dead Korean MMOs, and I believe I can bring practical experience to the table.

**Comment by jwaldmann** [comment]
also, this seems related: https://mosh.org/#techinfo (see "instant local echo", "predictive model")

**Comment by jgotoh** [comment]
Hello,

first, thank all of you for your suggestions!
Unfortunately I didn't even get too far, because the project is actually harder than I expected it to. Investigating error handling (by using graded monads etc) and actual synchronisation is still an open issue, but I'll be happy researching your suggestions when I get there.

I just uploaded the current state to GitHub:
https://github.com/jgotoh/distributed-frp-dunai

It contains the library and an example application (distributed-paddles, a Pong clone).

Currently the library offers a Client/ Server infrastructure, exchange of states between hosts and joining sessions.
Also there are modified versions of reactimate for Clients and Servers to handle receiving and sending inputs/ states.

Some info about it:

- no error handling and synchronisation mechanisms (yet)
- Clients run FRP and send their inputs to a Server
- the Server executes the inputs, and simulates the states of the players and the ball
- every frame, the Server sends its simulated states to the clients (who display it then)
- `run_test` is a script for easier startup of distributed-paddles (else you would have to write all the command line arguments to decide what to start manually)

There is currently a space leak (but I did not get to investigate it yet) somewhere, so commands issued by clients are executed after (reeeally) long delays.

The next steps will be solving the leak, and then implementing synchronisation (by using techniques like @jwaldmann posted here).

You can try it out, if you have any questions, I'll try to send an answer more quickly than this time :)

Cheers, Julian (formerly boogledekoog)

**Comment by ivanperez-keera** [comment]
@jgotoh I hope progress is going well. There is a PR that addresses a leak with a newtype (this is trivial to add locally just to test it). I'd be curious to know if this solves your issue.

**Comment by jgotoh** [comment]
@ivanperez-keera Progress is going well, yes! The leak that occurred was actually just some fault on my side, unrelated to dunai. Working with dunai is a breeze :)

Currently I am implementing Time Warp synchronisation, which is about rolling back reactimate to previous states to be able to issue new input to already executed signal functions. Your Back to the Future paper helps a lot, especially the part about temporally consistent vs temporally directed signal functions.

**Comment by ivanperez-keera** [comment]
I never followed up on this. Should this be documented in the repo (e.g., in the README)? Happy to do so. If so, please re-open this ticket, tell me what to add, and we'll add it and close it with a merge commit.
