### ISSUE TITLE
Add API changes to readme

### ISSUE THREAD

**Issue by turion** [ivanperez-keera/dunai#14]
Version 0.2 saw a lot of renames like `liftMStreamF` to `arrM` and `MStreamF` to `MSF`, these should be outlined in the readme.

**Comment by ivanperez-keera** [comment]
I'll see your bet and raise you a readme cleanup and micro-tutorial.

**Comment by ivanperez-keera** [comment]
For a newer paper I included in the repo a list of all the examples in the paper, with the latest syntax.

**Comment by ivanperez-keera** [comment]
It's perfectly reasonable to do this in two steps. Nevertheless: https://github.com/ivanperez-keera/dunai/issues/26

**Comment by turion** [comment]
The micro tutorial is #19. So all that remains in this issue are documenting renames from publication versions (ICFP 2016, possibly HAL 2017) to the current version.

**Comment by turion** [comment]
The micro tutorial is #19. So all that remains in this issue are documenting renames from publication versions (ICFP 2016, possibly HAL 2017) to the current version. Also, this should go into the CHANGELOG, not in the README, right?

**Comment by ivanperez-keera** [comment]
I'm not sure either is the place for this.

I think the best would be to create a separate file with the examples in the papers, and always keep it up to date. For the paper, which is always kept up to date. For other talks/projects, it could be here or, if it gets too complicated, be where the slides are (different repo/location).

**Comment by ivanperez-keera** [comment]
Since we have split this issue into several others, I'm closing this now.
