### ISSUE TITLE
Select issues for Hacktoberfest

### ISSUE THREAD

**Issue by turion** [ivanperez-keera/dunai#145]
We could tag some of the issues here with [Hacktoberfest](https://hacktoberfest.digitalocean.com/details). (Feel free to close if you think this is not a good idea.)

**Comment by ivanperez-keera** [comment]
I've created a few very simple issues for people who just want to get started. Most have to do with documentation.

I'd love the close the VectorSpace stuff that we have open, especially since simple-affine-space is a separate library from Yampa now, but that seems more for us than for beginners.

**Comment by turion** [comment]
This issue here can serve as a general landing page for Hacktoberfest contributors if you want.

**Comment by ivanperez-keera** [comment]
I'd suggest this issue to discuss new proposals, and [this link](https://github.com/ivanperez-keera/dunai/issues?q=is%3Aopen+is%3Aissue+label%3Ahacktoberfest) as a "landing page" or link we share with people.

**Comment by ivanperez-keera** [comment]
As we are nearing the end of the month, I think we can close this issue. Any discussions regarding other candidates for hacktoberfest can take place in the corresponding issue comments.
