### ISSUE TITLE
Bearriver: define accumBy

### ISSUE THREAD

**Issue by ivanperez-keera** [ivanperez-keera/dunai#149]
The function `accumBy` is pretty useful, but missing (we have `accumHoldBy`).

It would be useful to include it.

**Comment by ivanperez-keera** [comment]
Subtask of #40 .

**Comment by chriz-keera** [comment]
Hi,

could this be a solution for `accumBy`:

```
accumBy :: Monad m => (b -> a -> b) -> b -> SF m (Event a) (Event b)
accumBy f b = feedback NoEvent $ arr $ \(a, b') ->
  let eB = (fmap f b') <*> a
  in let b'' = if isEvent eB then eB else b'
     in (b'', b'')
```
And if so, is there a way to put the two lets in one?

**Comment by turion** [comment]
I'd rather use `accumulateWith` and `mapMaybeS` from `dunai` and pre- & postcompose with the isomorphism `Maybe a = Event a`. In fact, there could be a function `mapEventS :: SF m a b -> SF m (Event a) (Event b)`.

**Comment by chriz-keera** [comment]
What do you think about this?

```
accumBy :: Monad m => (b -> a -> b) -> b -> SF m (Event a) (Event b)
accumBy f b = mapEventS (accumulateWith (flip f) b)                                        
  where
    mapEventS :: Monad m => MSF m a b -> MSF m (Event a) (Event b)
    mapEventS msf = proc eventA -> case eventA of
      Event a -> arr Event <<< msf -< a
      NoEvent -> returnA           -< NoEvent
```

**Comment by turion** [comment]
Sounds good to me in principle. I'd make mapEventS top level though, document it, and use $ in the definition of accumBy.
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by chriz-keera** [comment]
Thanks for the help!
