### ISSUE TITLE
Add stack support

### ISSUE THREAD

**Issue by turion** [ivanperez-keera/dunai#15]
We should give stack users the possibility to build dunai with stack easily, and get dunai on stackage.

**Comment by turion** [comment]
Creating a stack .yaml should be doable by me, getting dunai on stackage is probably a separate issue.

**Comment by ivanperez-keera** [comment]
Just as an example: I recently had to do this for Yampa: https://github.com/ivanperez-keera/Yampa/blob/develop/stack.yaml

I honestly do not know whether it should have more.

Yes, dunai and BearRiver should be on stackage.

**Comment by ivanperez-keera** [comment]
I've added the label hacktoberfest to see if we can get a bit of external help to complete this.
