### ISSUE TITLE
Link to talks on FRP and MSF from Scala perspective

### ISSUE THREAD

**Issue by ivanperez-keera** [ivanperez-keera/dunai#156]
Someone recently gave a talk about Monadic Stream Functions and an implementation in Scala.

It would be useful to link to their project from our README.

**Comment by KatSaldivar** [comment]
Hi! Can you clarify what project are you are referring to? Is it the Scala project or the project of this person who gave the talk? I did a search for Monadic Stream Functions in Scala and there were a few results but none that obviously stood out as being the project you were referring to.

**Comment by ivanperez-keera** [comment]
Hi @KatSaldivar . Thanks for taking a look! :)

I was referring to this particular work:

https://twitter.com/typelevel/status/1142391027732320257

I knew there was the talk. 13minutes into the talk, @diesalbla presented Monadic Stream Functions, and I assumed there would be an implementation in scala somewhere. Perhaps the author of the talk can confirm.

I suggest:
- Introducing a section after 'Further reading' called 'See also'
- Putting a link to the talk within that section, with using the title for the link, followed by a very short summary (5-10 words).
- If there is an implementation, linking to it.

Have you found any other implementations, by the way?

**Comment by ivanperez-keera** [comment]
Add links to also the following two talks by the same author, either as part of this issue or as a separate issue:

https://skillsmatter.com/skillscasts/12542-london-scala-users-group

https://skillsmatter.com/skillscasts/12819-introduction-to-functional-reactive-programming-in-scala

**Comment by ivanperez-keera** [comment]
Skillsmatter is, at least temporarily, closed, and links no longer work. Closed with the link provided by @Rizary .
