### ISSUE TITLE
Reorg: unify transformer lifting and running

### ISSUE THREAD

**Issue by turion** [ivanperez-keera/dunai#16]
@ivanperez-keera, we have a lot of different lifting and running functions around, do you have an opinion on what we should keep and what should be removed? I think we should go with one of the general approaches and reformulate (with inlining) everything in terms of it.

**Comment by ivanperez-keera** [comment]
We need to separate the library from ideas/research well. I'm happy picking one approach (any), and moving everything else outside or, at least, hiding it in the export list of each module.

We can then study if there is a more general way of doing this.

**Comment by turion** [comment]
Agree, this needs more research.

Currently, there seems to be no approach that encompasses _all_ transformers we're currently supporting. It usually fails with `ListT` or `ExceptT`, those are a bit special (or just don't fit into our current approach).

I think we should close this issue now and return to it once we've done the necessary research.

**Comment by turion** [comment]
I thought about this more, and I think most research on this is already done. The lifting functions fall in two categories:

* "Hoisting functions", those which only influence input, output and side effect types. I've written down the most general (in a precise mathematical sense) such function now, it's basically an abstraction of your `liftS`.
* "Handling functions", those that change control flow, such as exception handling and `ListT` broadcasting. I think these can be very general. Your `transG` captures some of them, but I'm not sure whether it captures all, I think not.

For the moment, I'm content with the reformulating most wrapping/running functions with this one very compact approach, and a few others with `transG`. We can think about the handling/control flow aspect more in the future. Sending a PR.

**Comment by ivanperez-keera** [comment]
Solved by @turion  in the branch https://github.com/ivanperez-keera/dunai/tree/develop_general_lifting.
