### ISSUE TITLE
Examples from FRP refactored Section 3

### ISSUE THREAD

**Issue by chriz-keera** [ivanperez-keera/dunai#163]
Hi,

I tried to tackle #95, but I got compiling errors. So I thought, let's start with Section 3 instead.
Here are my first steps: https://github.com/chriz-keera/dunai/tree/develop-frprefactored-examples/examples/frprefactoredsec3

Unfortunately, the `testSerial`example does not run as expected ([here is the step-by-step documentation](https://github.com/chriz-keera/dunai/blob/develop-frprefactored-examples/examples/frprefactoredsec3/README.md). Any idea what's going on here?

**Comment by turion** [comment]
I believe we have mixed up [`repeat`](https://hackage.haskell.org/package/base-4.12.0.0/docs/Prelude.html#v:repeat) with [`replicate`](https://hackage.haskell.org/package/base-4.12.0.0/docs/Prelude.html#v:replicate). Classic.

**Comment by ivanperez-keera** [comment]
Yes, I remember seeing that mistake in the paper.

Also relevant: https://github.com/ivanperez-keera/dunai/tree/develop/examples/paper/src

**Comment by chriz-keera** [comment]
Thanks! `replicate` works. Refs #106.
