### ISSUE TITLE
Help setting up repository for cabal user by adding cabal.project

### ISSUE THREAD

**Issue by Rizary** [ivanperez-keera/dunai#165]
Since I am a cabal user, I need to add `cabal.project` to start working on #96. 

So I start this issue, and add PR separately to add `cabal.project`. Cabal is already version 3.0 and by only using `cabal build` we can build the project easily. However, I know that several projects in the folder `examples` can't be built. But most of them not because of `cabal` behavior.

Adding `cabal.project` file to your repo helped cabal's user a lot.

**Comment by ivanperez-keera** [comment]
I'm happy supporting newer versions of cabal, but I see these packages as separate (but related).

Doing this right suggests that we re-organize stuff.

As a first attempt, I've put all the files into subdirs.

https://github.com/ivanperez-keera/dunai/tree/develop-reorg

@turion Would you find a repo organized this way easier to navigate? Do you think it's an improvement?

**Comment by turion** [comment]
I find that a great organisation! It needs some tweaks in `.travis.yml` still.

**Comment by ivanperez-keera** [comment]
Correct, and a lot of the README.md might have to come to the top level. There would be some duplucation there, unless we can just link to the one in `dunai/`.

**Comment by ivanperez-keera** [comment]
You can just link to it: https://github.com/ivanperez-keera/dunai/tree/develop-test-readme

**Comment by ivanperez-keera** [comment]
There's some bug on github (just reported it). Your last comment "Ah, yes. The issue there..." should come before my last comment "You can just link to it".

**Comment by turion** [comment]
> You can just link to it: https://github.com/ivanperez-keera/dunai/tree/develop-test-readme

What kind of link is that? A Linux symlink?

**Comment by turion** [comment]
Ah, yes. The issue there is that the top level readme is displayed on github, but the readme in `dunai/` is displayed on hackage. Ideally, those two should agree, but I don't know how to do that reasonably. In `rhine`, I opted for a hyperlink on hackage to github..

**Comment by ivanperez-keera** [comment]
Yes
.
