### ISSUE TITLE
Function `liftMSF` mentioned but not available

### ISSUE THREAD

**Issue by chriz-keera** [ivanperez-keera/dunai#168]
In the documentation of `embed` a function called `liftMSF` is mentioned ([see here](https://github.com/ivanperez-keera/dunai/blob/57e95a8966f99cf54bbbbf2133f56c4a345e95af/src/Data/MonadicStreamFunction/InternalCore.hs#L119)).

Searching for it via `grep` in `dunai` shows that currently unused code still contains the function. So I guess the function got renamed.

```
dunai$ grep -nHre liftMSF --include='*.hs'
src/Data/MonadicStreamFunction/InternalCore.hs:119:-- To explore the output progressively, use 'liftMSF' and '(>>>)'', together
src/Control/Monad/Trans/MSF/List.hs:36:-- sequenceS = foldl (<+>) arrowzero . map liftMSFTrans
examples/bearriver/src/FRP/BearRiver.hs:286:  -- runMaybeT $ MSF.reactimate $ liftMSFTrans (senseSF >>> sfIO) >>> actuateSF
examples/bearriver/src/FRP/BearRiver.hs:301:       -- actuateSF    = arr (\x -> (True, x)) >>> liftMSF (lift . uncurry actuate) >>> exitIf
examples/classicfrp/GTest.hs:65:  MSF.reactimate $ sense >>> liftMSFPurer (return.runIdentity) sfIO >>> actuate
```

**Comment by turion** [comment]
Yes, this should now be `arrM`.

**Comment by turion** [comment]
See e.g. ce9fe12825e618773def0592789e3ba787d1b66b for an analogous fix.
