### ISSUE TITLE
listToMaybeS is incorrect

### ISSUE THREAD

**Issue by turion** [ivanperez-keera/dunai#170]
I believe the function `listToMaybeS` is broken. The correct solution could be:

```
exceptToMaybeS :: Monad m => MSF (ExceptT e m) a b -> MSF (MaybeT m) a b
exceptToMaybeS = morphS $ MaybeT . fmap (either (const Nothing) Just) . runExceptT

listToMaybeS :: Monad m => [a] -> MSF (MaybeT m) arbitrary a
listToMaybeS = exceptToMaybeS . runMSFExcept . sequence . map (step . const . return . (, ()))
```

As a low-hanging fruit for beginners who want to contribute, take this correct code and insert it in `Control.Monad.Trans.MSF.Maybe`, and fix the imports.

**Comment by ivanperez-keera** [comment]
@turion I am going to release a new version of dunai. Do you want to put this in or wait for the contribution?

**Comment by turion** [comment]
@ivanperez-keera When are you going to release? Shall I squeeze this in for the new version? (Would be better)

**Comment by ivanperez-keera** [comment]
I want to release dunai today. Bearriver is currently broken because of this (see #179 ). Also, not the end of the world but the build icon on dunai's page says "broken" because bearriver fails to compile.

I do not really understand the expression you wrote. Breaking it up by hand, I get:

```
snd exp1

 where
    exp1 :: (Maybe [()], String)
    exp1 = runWriter exp2

    exp2 :: WriterT String m (Maybe [()]) 
    exp2 = runMaybeT exp3

    exp3 :: MaybeT (WriterT String m) [()]
    exp3 = flip embed [1..] topMSF

    topMSF :: Monad m => MSF (MaybeT (WriterT String m)) a ()
    topMSF = helloMSF >>> writerMSF

    helloMSF :: Monad m => [String] -> MSF (MaybeT m) a String 
    helloMSF = listToMaybeS ["H", "el", "lo"]

    writerMSF :: Monad m => MSF (MaybeT (WriterT String m)) String ()
    writerMSF = arrM (lift . tell)   -- operationally may be the same
                                     -- but the level of abstraction is different
```

So I think I would expect "", but my reasoning may be wrong at some step (I did this by hand).

**Comment by turion** [comment]
My example is a bit cryptic, apologies. It's meant to produce some outputs that come from a list and then stop.

You are right that currently, this evaluates to `""`, but my question is actually whether this is intended behaviour for `listToMaybeS`. After having played around a bit I'm pretty convinced that this is not intended or useful. It should throw the exception _after_ having emitted all list elements, and not before.

If that's ok with you I'll create a PR with a fix, a regression test and some improved docs. I'll also tets whether this fixes any other issues (#108).

**Comment by turion** [comment]
This commit is the culprit: f4fc0ca25c12c726ee0b3970fbebda4d300ce3ef

Specifically, this change here:
```
-- | Preprends a fixed output to an 'MSF'. The first input is completely
 -- ignored.
 iPost :: Monad m => b -> MSF m a b -> MSF m a b
-iPost b sf = MSF $ \_ -> return (b, sf)
+iPost b sf = sf >>> (feedback (Just b) $ arr $ \(c, ac) -> case ac of
+  Nothing -> (c, Nothing)
+  Just b' -> (b', Nothing))
```

@ivanperez-keera you might want to double check whether the behaviour of `iPost` is actually what you are expecting.

**Comment by ivanperez-keera** [comment]
@turion I do not understand why `iPost b sf` is not the same as `sf >>> iPre b`.

Yampa itself does not offer an `iPost`.

**Comment by turion** [comment]
> @turion I do not understand why `iPost b sf` is not the same as `sf >>> iPre b`.
> 
> Yampa itself does not offer an `iPost`.

What should be the semantics of iPost in your opinion then?

E.g. what should be the output of `embed (iPost 23 $ arr id) [1..5]`? Currently, it's `[23,2,3,4,5]`. The output of `embed (arr id >>> iPre 23) [1..5]` is `[23,1,2,3,4]` though. I think you should decide (in a separate issue) which of those it should be and I'll add a unit test that fixes the behaviour.

**Comment by ivanperez-keera** [comment]
I don't have a particular need for `iPost`, to be honest. You can always `iPre b . sf` or `iPre b <<< sf` if it's a matter of style, or just `sf >>> iPre b` if you don't mind putting it afterwards.

**Comment by ivanperez-keera** [comment]
Going back to your original question: yes, I would expect to be able to say something like `listToMaybeS ["H", "el", "lo"] >>> arrM (tell >>> lift)`, and that to give me at the very end the word "Hello" in the writer log.

I think that was the intended meaning of `listToMaybeS`: to give you the first element and a continuation, the second element and a continuation, etc. until there is nothing more.

Generally, I find it complicated to understand what you should get at the end due to having the monads in the stack in that order, due to where `embed` is used, and due to the use of `runWriterT` and `runMaybeT` after `embed`.

**Comment by turion** [comment]
Hmmm ok, then I guess the issue is rather that the test case is so complicated. Maybe it was easier if it was just `IO`. How about this:

```
ghci> runMaybeT $ reactimate $ listToMaybeS ["H", "el", "lo"] >>> arrM (putStrLn >>> lift)
H
el
lo
Nothing
```

I just took `WriterT` so it's pure.

**Comment by ivanperez-keera** [comment]
I have tried a few things in my terminal and I agree with you that the behaviour that is expected is what you suggest, and not what we currently implement. This was broken by my re-write of `iPost` in a prior commit. If the behaviour of `iPost` is restored, then `listToMaybeS` behaves as expected.

I'll accept the patch. Just to make you aware, over the next few weeks, I'll probably re-write the code to eliminate the use of GHC extensions and to simplify all the functions if I see a way.

By the way, the next function in the same file (`runMaybeS`) defines, locally, `eitherToMaybe`.

Thanks, @turion !
