### ISSUE TITLE
Document haskell titan support

### ISSUE THREAD

**Issue by myroslambda** [ivanperez-keera/dunai#176]
[Haskell Titan](https://github.com/keera-studios/haskell-titan) now supports bearriver with extra flags of two packages:

- https://hackage.haskell.org/package/titan-debug-yampa
- https://hackage.haskell.org/package/titan-record-yampa

This makes it possible to just recompile applications and start debugging with the interactive GUI.

It would be helpful if this could be documented in dunai's README and in the bearriver package, so that people refer to titan if they want to do testing.

**Comment by turion** [comment]
That sounds cool! Is there some example bearriver test project somewhere that we could point to?

**Comment by myroslambda** [comment]
In principle, this should work with any Yampa example too. The titan repo has examples.

The recording and debugging facilities are added at the top level (in the call to reactimate), by providing some additional arguments. For debugging with the GUI, the arguments are these:

https://github.com/keera-studios/haskell-titan/blob/develop/titan-debug-yampa/examples/BouncingBall.hs#L21-L25

For record-and-deplay, there is no example, but it takes 2 lines to add to any existing Yampa application: instead of using reactimate, use `FRP.Titan.Record.Yampa.reactimateRecord` and provide an additional `Just ("somefile.ytr", RecordWriteOnly)`.

Two suggestions (not for this repository): making an existing game support these out of the box with cabal flags, and making it possible to call via command line with different arguments to run in debug/record/replay/normal mode.

**Comment by ivanperez-keera** [comment]
I just updated haskanoid to work with this: https://github.com/ivanperez-keera/haskanoid/tree/develop-haskelltitan.

Also, haskanoid is a game written for educational purposes, so it's important that it is not polluted with too many flags or extra arguments everywhere. Before merging, I am trying to come up with a good strategy to reduce the negative impact, keep the learning curve flat-ish, and maintain all of this with less effort in the future (for me).

**Comment by ivanperez-keera** [comment]
I had completely forgotten that this had been done. I've been using dunai for some testing work and it would be awesome to be able to plug in titan and move around the timeline.
