### ISSUE TITLE
HLint.hs and hlint.hs are the same filename on some systems, namely Mac OS

### ISSUE THREAD

**Issue by Linearity** [ivanperez-keera/dunai#182]
Could these two files have different names? They make branching and re-basing almost impossible on Mac OS or any other file system where the two files cannot be distinct, since Git always complains that one or the other is missing.

**Comment by ivanperez-keera** [comment]
Yes! We had this problem elsewhere too. This should happen for all projects.

This was my mistake: I had never used Mac OS when I originally made that decision, and (me and many other people I worked with) went along with it in every project ever since.

**Comment by ivanperez-keera** [comment]
To solve this issue in the same way as in other repos:

- Rename the actual hlint file to: `tests/HLint.hs`
- Rename the haskell program that executes hlint to: `tests/HLintMain.hs`
