### ISSUE TITLE
hlint.hs has incorrect header comments

### ISSUE THREAD

**Issue by turion** [ivanperez-keera/dunai#186]
The first few lines of `tests/hlint.hs` talk about Ed Kmett and `lens`, not `dunai`.

**Comment by ivanperez-keera** [comment]
That file is completely taken from the lens project, I believe.

**Comment by ivanperez-keera** [comment]
I am not an expert in copyright law or a lawyer. I believe the right way to solve this is to change the maintainer, and change the mention of lens, but keep the (c) notice with Kmett's name there.
