### ISSUE TITLE
bearriver: reactimate skips first time step

### ISSUE THREAD

**Issue by Linearity** [ivanperez-keera/dunai#188]
@turion A `switch` combination, after my suggested changes in 0.13.1, does indeed divide by zero if its second phase runs `derivative`. (in response to your [comment](https://github.com/ivanperez-keera/dunai/pull/177#issuecomment-578523167))

Even in prior versions, `reactimate` is written as if it would also divide by zero when running `derivative` as the _first_ phase of a `switch` combination. In its definition, `senseFirst` takes the initial sensation value and combines it with a time step of `0`:

    senseSF     = MSF.switch senseFirst senseRest
    senseFirst  = constM senseI >>> (arr $ \x -> ((0, x), Just x))

However, this is misleading. `(0, x)` here is never used: it is immediately replaced by the output of `senseRest`, because `senseFirst` immediately signals (with `Just x`) to `MSF.switch` that `senseRest` should take over. It skips the case where time, and therefore the time _step_, is equal to zero.

Thus in prior versions, both `reactimate` and `switch` avoided zero time steps by skipping the initial values and calculating only values at local times later than zero.

For animation applications this behavior of `switch` is jarringly obvious, and I am glad that it is fixed. The same behavior in `reactimate` is hard to see because it happens before the animation begins, but it remains somewhat unsatisfying.

A simple change to `senseSF` rectifies this:

    senseSF     = MSF (const (do a0  <- senseI
                                 return ((0, a0), senseRest a0)))

Of course, this introduces a new case where `derivative` divides by 0, though in my mind not an unexpected one.

**Comment by ivanperez-keera** [comment]
@Linearity Two main questions to help make decisions:

- What happens in Yampa if you have a derivative at time 0?

- Can this be written cleanly without access to the `MSF` value constructor? (That was the point of using `switch`.)

**Comment by ivanperez-keera** [comment]
I'm adding this to the release at the end of February. If anything needs to change here, I'd really like to have reached a decision by then and put this in a new release of bearriver that accompanies dunai 0.7 :)

**Comment by Linearity** [comment]
> What happens in Yampa if you have a derivative at time 0?

It gives you `zeroVector` at time 0 and then the difference quotient afterward.

    derivative = SF {sfTF = tf0}
        where
            tf0 a0 = (derivativeAux a0, zeroVector)
            derivativeAux a_prev = SF' tf -- True
                where
                    tf dt a = (derivativeAux a, (a ^-^ a_prev) ^/ realToFrac dt)

Really, `BearRiver.derivativeFrom` is the same as `derivativeAux` above, just in a `ReaderT` environment. If I change it to override the first output value using `initially zeroVector` it survives the initial frame without issue.

> Can this be written cleanly without access to the MSF value constructor? (That was the point of using switch.)

Yes, this works for me:

    senseSF     = MSF.switch senseFirst senseRest
    senseFirst  = proc _ -> do
                     a0      <- constM senseI    -< ()
                     done    <- iPre Nothing     -< Just a0
                     returnA -< ((0, a0), done)
    senseRest a = constM (sense True) >>> (arr id *** keepLast a)

**Comment by ivanperez-keera** [comment]
Hmm, this will execute `senseI` twice, won't it?

**Comment by Linearity** [comment]
Ah, yes it does. `a0` is not evaluated twice but the `IO` action is performed twice.

**Comment by ivanperez-keera** [comment]
@Linearity Have you been able to find a better way of writing this without duplicating the action?

I want to put a version out soon. We are a bit late with this release.

**Comment by ivanperez-keera** [comment]
This fix is ready to be tested in: https://github.com/ivanperez-keera/dunai/tree/develop-reactimate-firstsample

I have tried it with Haskanoid and with the example above, and it seems to work. Please let me know ASAP if you can.

Pinging @Linearity for awareness.

Thanks!
