### ISSUE TITLE
Bearriver: reactimate space leak

### ISSUE THREAD

**Issue by walseb** [ivanperez-keera/dunai#194]
Hi! 
I have run this: `reactimate (return NoEvent) (\ _ -> return (0.1, Nothing)) (\_ _ -> pure False) (constant ())` on both yampa and bearriver. In yampa the memory is stable while in bearriver it leaks.
I ran it through a profiler and got this:
https://github.com/walseb/bearriver-space-leak/blob/master/ExampleBearriver/ExampleBearriver.svg
Where `morphGS/unMSF/reactimate/reactimateExcept/reactimateB/reactimate/main` seems to be causing the problems (https://github.com/walseb/bearriver-space-leak/blob/master/ExampleBearriver/ExampleBearriver.hp#L13066)

Here is my code if you want to run it yourself:
https://github.com/walseb/bearriver-space-leak/blob/master/ExampleBearriver/src/Main.hs
Thanks for this package!

**Comment by ivanperez-keera** [comment]
Hi!

I'll take a look.

Thanks!!

**Comment by turion** [comment]
That's a great find!

To debug in `dunai` alone:

```haskell
import Control.Arrow
import Data.Functor.Identity
import Data.Maybe

import Control.Monad.Trans.Identity
import Control.Monad.Trans.Reader

import Control.Monad.Trans.MSF.Except
import Control.Monad.Trans.MSF.Reader
import Data.MonadicStreamFunction
import Data.MonadicStreamFunction.Core
import Data.MonadicStreamFunction.InternalCore
import Data.MonadicStreamFunction.Util

main = reactimateB
    $ switch
        (constM (return ()) >>> (arr $ \x -> ((0, x), Just x))) (\a -> constM ((\_ -> return (0.1, Nothing)) True) >>> (arr id *** keepLast a))
        >>> morphS (return . runIdentity) (runReaderS $ (arr . const) ())
        >>> (arr (\x -> (True, x)) >>> arrM (uncurry (\_ _ -> pure False)))
    where
        keepLast a = MSF $ \ma -> let a' = fromMaybe a ma in return (a', keepLast a')
```

**Comment by turion** [comment]
I reduced the example to:

```haskell
import Control.Arrow
import Data.Functor.Identity
import Data.Maybe

import Control.Monad.Trans.Identity
import Control.Monad.Trans.Reader

import Control.Monad.Trans.MSF.Except
import Control.Monad.Trans.MSF.Reader
import Data.MonadicStreamFunction
import Data.MonadicStreamFunction.Core
import Data.MonadicStreamFunction.InternalCore
import Data.MonadicStreamFunction.Util
```
```
main = reactimateB
    $ arr (const Nothing)
    >>> keepLast ()
    >>> arr (const False)
    where
        keepLast a = MSF $ \ma -> let a' = fromMaybe a ma in return (a', keepLast a')
```
It seems that the space leak is in `keepLast`. The `fromMaybe` builds up thunks that don't get evaluated.

We can force them to be evaluated by using the value:

```haskell
main = reactimateB
    $ arr (const Nothing)
    >>> keepLast ()
    >>> arrM print
    >>> arr (const False)
    where
        keepLast a = MSF $ \ma -> let a' = fromMaybe a ma in return (a', keepLast a')
```
Or we can introduce strictness in `keepLast`:
```haskell

main = reactimateB
    $ arr (const Nothing)
    >>> keepLast ()
    >>> arr (const False)
    where
        keepLast a = MSF $ \ma -> let a' = fromMaybe a ma in a' `seq` return (a', keepLast a')
```
I think the latter approach could be merged into `bearriver`.

This shows once again that using the `MSF` constructor in the wild is dangerous and should be forbidden, if even an expert can introduce a non-obvious bug. Possibly, `keepLast` should be rewritten with `dunai` components, or put in the standard library if this isn't possible.

**Comment by ivanperez-keera** [comment]
I can confirm that I can reproduce the leak.

**Comment by ivanperez-keera** [comment]
@turion 's solution with `seq` seems simple enough. The function `reactimate` in `bearriver` is currently written using the `MSF` constructor, so it seems reasonable to apply this change there. If we can later re-write `reactimate` without access to `MSF`, then we may need to evaluate this again.

The following profile demonstrates @walseb 's example with @turion's `seq`-based solution:

![Screenshot from 2020-03-14 21-20-21](https://user-images.githubusercontent.com/1162320/76693365-00749c80-663a-11ea-9559-2c15166a62ce.png)
