### ISSUE TITLE
Bearriver: Generic 1D vector space instance

### ISSUE THREAD

**Issue by walseb** [ivanperez-keera/dunai#198]
Right now tuple vector space instances have the generic type constraint of `Eq` and `Floating` but 1D vectors are restricted to Double and Float. It's possible to declare a generic 1D vector instance using a linear V1 like this:
```
instance (Eq a, Floating a) => VectorSpace (V1 a) a where
-- Same content as the Double and Float instances but that also unpacks V1 during calculations
```
But when I try to declare an unwrapped instance like this:
```
instance (Eq a, Floating a) => VectorSpace a a where
-- Same content as the Double and Float instances
```
I get this error: `Functional dependencies conflict between instance declarations`
However it does work if I modify the vector space typeclass constraints from this:
```
class (Eq a, Floating a) => VectorSpace v a | v -> a where
```
to this
```
class (Eq v, Floating v, Eq a, Floating a) => VectorSpace v a | v -> a where
```
but then it's not possible to define anything other than 1D vectors, and I also get into trouble if I declare both V2 instances and unwrapped instances because of some reason.
I have looked at [other vector space packages](https://hackage.haskell.org/package/vector-space) but none of them seem to have a generic 1D vector space instance so maybe this problem is inherent in this approach? I'm just opening this issue in case there is an easy fix because I'm not sure what's wrong with it. Thanks!

**Comment by turion** [comment]
I believe this is a general problem with Haskell's type classes, and one has to work around it with a `newtype` (I guess this is your `V1`).

Your last approach doesn't work because one typically can't define a `Floating` instance for a vector space.

**Comment by ivanperez-keera** [comment]
I concur.

Apologies for the delay in answering, I somehow missed this message. Thank you @turion for responding to @walseb  :)

I assume this is answered then. Closing. Please reopen if not :)
