### ISSUE TITLE
Announce dunai 0.7.0, dunai-test 0.7.0, and bearriver 0.13.1.2

### ISSUE THREAD

**Issue by ivanperez-keera** [ivanperez-keera/dunai#204]
@turion Could you (or anyone who wants to and has the necessary accounts) announce the new versions of dunai, dunai-test, and bearriver, on social media + reddit + etc?

I normally announce on:
- Twitter
- Facebook (Programming in Haskell)
- Reddit
- Linkedin

When it's a major release, also haskell-cafe.

**Comment by turion** [comment]
This is important to do, but it's also one of the things that I systematically do worse than you ;) I don't have accounts for Twitter, Facebook or Reddit, and no intention to set them up.

**Comment by ivanperez-keera** [comment]
Done:
- https://www.facebook.com/groups/programming.haskell/permalink/4001496683194636/
- https://twitter.com/IvanPerezKeera/status/1252552118730457089
- https://www.linkedin.com/posts/ivanperezdominguez_ivanperez-keeradunai-activity-6658320018570305536-1N0a
- https://www.reddit.com/r/haskell/comments/g5d7ul/ann_extensible_frp_dunai_07_dunaitest_07_and/
