### ISSUE TITLE
Bearriver's Event is missing the Functor, Monad and Applicative instances

### ISSUE THREAD

**Issue by ivanperez-keera** [ivanperez-keera/dunai#212]
Bearriver's Event is missing the Functor, Monad and Applicative instances, which exist in Yampa and are very useful.

This is a great candidate for something that could be introduced by a near beginner: the instances are the same as Maybe's, with the following replacement: `Just` => `Event`, `Nothing` => `NoEvent`, and `Maybe` = `Event`.

Just know that, because bearriver and dunai need to be backwards compatible with GHC versions prior to GHC 8.6, you can't use `DerivingGeneric` or `DerivingVia`.

I'm marking this for the next milestone, but it can also be a small release that goes out very soon.

**Comment by walseb** [comment]
Functor and Applicative are [already in](https://github.com/ivanperez-keera/dunai/blob/develop/examples/bearriver/src/FRP/BearRiver.hs#L179), I will try making a monad instance to get to know events better. Thanks for creating these issues!

**Comment by geroldmeisinger** [comment]
Why do we need `Event` instead of `Maybe` anyway if they are "isomorphic"? Seems like there are a lot of other instances missing as well, https://hackage.haskell.org/package/base-4.17.0.0/docs/Prelude.html#t:Maybe

**Comment by ivanperez-keera** [comment]
In bearriver, the reason to have `Event` is because Yampa has them. Bearriver needs to mimic Yampa's interface.

In Yampa,the reason to have `Event` is to semantically indicate with the type what you mean (declarative programming). Also, the `Event` and `EventS` modules in Yampa are very expressive, and you can go a long way without having to use the constructors. So, you can treat `Event` as an abstract data type. If tomorrow we find that the best way to improve Yampa is to change the `Event` constructors, your program doesn't have to change.

If there is an instance that exists in Yampa and not here, file an issue here. If there is an instance that `Maybe` has, `Event` doesn't have, and you need, file an issue in Yampa's repo.

**Comment by geroldmeisinger** [comment]
> In Yampa,the reason to have `Event` is to semantically indicate with the type what you mean (declarative programming).

But couldn't we use an type alias as well?

> If tomorrow we find that the best way to improve Yampa is to change the `Event` constructors, your program doesn't have to change.

..as long as the constructor doesn't change. In the meantime, why not use an alias?

**Comment by ivanperez-keera** [comment]
> > If tomorrow we find that the best way to improve Yampa is to change the Event constructors, your program doesn't have to change.
> ..as long as the constructors don't change.

I don't fully agree. You can write a lot of code without using the value constructors of `Event` (I suspect you can write pretty much everything you need to write in practice). If you use the functions in the API (like `noEvent`), but not the direct value constructors (like `NoEvent`), then your code becomes more forward-compatible. It's more resistant to changes to the implementation.

> > In the meantime, why not use an alias?

Abstraction, and hiding implementation details, helps convey what is meant and makes code more forward-compatible.
