### ISSUE TITLE
classicfrp & dunai-test are not on CI

### ISSUE THREAD

**Issue by turion** [ivanperez-keera/dunai#214]
The package in `examples/classicfrp` is not on Travis CI. Consequently, it stopped typechecking at some point when some refactoring was done.

It should be fixed and added to CI.

**Comment by turion** [comment]
Similarly, the `dunai-test` package should also be added.

**Comment by ivanperez-keera** [comment]
Adding dunai-test was a good addition, but it broke the CI build due to a missing `Functor` constraint.
