### ISSUE TITLE
Use nix & Cachix for faster CI and reproducible builds?

### ISSUE THREAD

**Issue by turion** [ivanperez-keera/dunai#216]
Competitor issue to #215.

I'm offering to set up nix files to build & test all of dunai and the other packages here. I believe that this would speed up build time because dependencies can be cached through nix.

Optionally, an external cache like https://cachix.org/ can be added, which further speeds up build times. The cache can be populated by building locally, i.e. `nix-build | cachix push`. For an example setup, see an analogous Gitlab config: https://gitlab.com/turion/wir-vs-virus/-/blob/master/.gitlab-ci.yml#L9

A big advantage is reproducible builds, i.e. the same build happens locally and on CI. This means that if the local build succeeds, it's virtually guaranteed that CI will pass. That's a speedup in dev time when pushing PRs.

Furthermore, with nix we can build all packages at once. Packages with dependencies (e.g. on `dunai`) will not need to rebuild or redownload their dependencies again. The build can be parametrised over environment variables that correspond to GHC versions. For an example, see https://github.com/sebastiaanvisser/clay/. It's possible to incorporate exceptions for specific packages.

If you think this might be useful, I'll set this up.

**Comment by ivanperez-keera** [comment]
The build file seems simple enough, but I don't use nix, I don't have the necessary knowledge to make an informed decision about this, and I don't have the time to learn it at the moment.

I prefer that we just go one step at a time.

**Comment by turion** [comment]
Ok
