### ISSUE TITLE
Evaluate compilation with GHC 8.10

### ISSUE THREAD

**Issue by ivanperez-keera** [ivanperez-keera/dunai#217]
To keep up with the latest developments of the GHC team, it would be good to evaluate if dunai and bearriver compile with the latest version of GHC (8.10) as of this writing, meaning:

- Compile everything with GHC 8.10, and see that it works. A minimal test would have to include dunai, bearriver, and dunai-test.

- Add it to the travis build. See that it passes.

- Document the state in the README.

This is a beginner-intermediate issue IMO. It would a good opportunity for someone who wants to contribute to the project but may not have a lot of expertise on FRP.

**Comment by oneEdoubleD** [comment]
Sounds like a good intro to the project, I'll take a look at this this week :)
