### ISSUE TITLE
Test where inlining will improve performance

### ISSUE THREAD

**Issue by turion** [ivanperez-keera/dunai#22]
In some places where functions are defined in terms of primitives (like `accumulateWith` and `integral` in terms of `feedback`), inlining might improve performance. This needs to be measured and implemented.

**Comment by ivanperez-keera** [comment]
The streaming package includes *microbechmarks* and a comparison with other packages: (see the graph at https://hackage.haskell.org/package/streaming). It would be a good idea to use that as a reference point as well to know how well Dunai could potentially do.

**Comment by ivanperez-keera** [comment]
In general, adding performance improvements needs to be done carefully, with proper metrics, systematically, unless the improvement is obvious and costs little. Performance improvements often result in code that is harder to understand, maintain or extend.

We are now evaluating to do this for the next year.

**Comment by ivanperez-keera** [comment]
We have now started a project to do this more generally, also for Yampa. We should re-visit this once that project yields results.

I can either close this for now or leave it open, but it may take moths or more than a year to revisit this.
