### ISSUE TITLE
Adding the bearriver arcade to readme

### ISSUE THREAD

**Issue by walseb** [ivanperez-keera/dunai#223]
Hi! I just published a bunch of arcade(ish) games I made made using bearriver! It shows you of the whole process from input management, game saving and loading, keeping a target framerate to rendering stuff with rotation and scale using SDL. Maybe bearriver should get a readme similar to yampa displaying these kinds of projects. Or maybe they should all be kept in the dunai readme since it's based on it. This is probably related to #220 
https://github.com/walseb/The_Bearriver_Arcade

One thing to note is that the games doesn't actually use anything that's not in yampa, but one of the games I'm working on does

**Comment by ivanperez-keera** [comment]
This is wonderful!!

Bearriver does not have a README (yet), but I agree that they should be added to Dunai's README. It could make sense to also add it to Yampa's: they could be useful for both projects!

**Comment by walseb** [comment]
Just a heads up for anyone trying it out, I just fixed a bug where the window didn't resize properly causing it to be unplayable on any machine but mine (because my window manager forces all windows into full-screen mode)

**Comment by ivanperez-keera** [comment]
@walseb Feel free to send a PR. I'd be happy to add this. These are fun to play, and useful resources for anyone who wishes to build their own.
