### ISSUE TITLE
Document compilation of Haskanoid with bearriver under Games section

### ISSUE THREAD

**Issue by ivanperez-keera** [ivanperez-keera/dunai#227]
Haskanoid can now be compiled with bearriver, which means that it could be included under the *Games* section.

This is a great candidate for a very low hanging fruit for someone who wants to contribute to an open source library.

I would like to ask any contributors to proceed as follows:

- Modify the README.md file to include an entry for Haskanoid under the existing Games section.
- Commit with the following message:
```
Add haskanoid entry to Games section. Refs #<this-issue-number>

Commit ivanperez-keera/haskanoid@cb50205bd8e1ec92eae3b689c1e4f3f2c260367d
added bearriver support to the official haskanoid distribution, making it
a candidate to be listed as a dunai/bearriver game.

Consequently, this commit modifies the README to list haskanoid in the Games section.

[ci skip]
```

Exaplanation:
- The first line gives a simple, one-line summary. The Refs at the end gives a quick link to this issue without having to go into the commit.
- The long description documents the issue. Pointing to the commit in Haskanoid helps understand why this is a good idea. See https://help.github.com/en/github/writing-on-github/autolinked-references-and-urls for documentation on the format to link to the issue.
- The [ci skip] at the end makes travis not re-compile dunai with this change: because it touches the `README.md` file only, the code has not changed and it will continue to compile and pass all tests if it did before.

You can modifiy that message if you think other information is relevant or helpful.

**Comment by mezzomondo** [comment]
Give me one minute and I'll take it.
