### ISSUE TITLE
Bearriver's parC incorrectly drops inputs

### ISSUE THREAD

**Issue by ivanperez-keera** [ivanperez-keera/dunai#228]
The implementation of `parC` does not behave like Yampa's. Because the list that `parC'` is passed only contains one SF, all elements from the input but one are discarded:

https://github.com/ivanperez-keera/dunai/blob/4de15d2e3f753a817be19e6a3bcba8f9978a9f11/dunai-frp-bearriver/src/FRP/BearRiver.hs#L466-L474

**Comment by turion** [comment]
The corresponding part in Yampa is:

https://github.com/ivanperez-keera/Yampa/blob/096e8ac5db59db5a34d9151b980047c0725ff0ac/src/FRP/Yampa/Switches.hs#L982

What's a test that passes for Yampa and fails for bearriver?
