### ISSUE TITLE
bearriver: Broken implementation of dlSwitch

### ISSUE THREAD

**Issue by walseb** [ivanperez-keera/dunai#230]
There appears to be a typo in the bearriver list module since `dlSwitch` is missing an implementation while `dlSwitch'` is defined just below without an explicit type signature. I'm not sure which is using the correct name because the function is not present in yampa.

Location:
https://github.com/ivanperez-keera/dunai/blob/develop/dunai-frp-bearriver/src/FRP/BearRiver/List.hs#L17

**Comment by ivanperez-keera** [comment]
The issues with this module are bigger. Also, this corresponds to Yampa's develop-games branch, which has additional features:

https://github.com/ivanperez-keera/Yampa/blob/develop-games/src/FRP/Yampa/Switches.hs#L1008-L1052
