### ISSUE TITLE
`bearriver`: Routing in dynamic collections

### ISSUE THREAD

**Issue by walseb** [ivanperez-keera/dunai#232]
Hi! So I'm working on a game in bearriver that has dynamic collections (in this case many enemies, bullets, etc), and for that bearriver has the list monad transformer (as discussed in #223), `dlSwitch` and `dpSwitchB`.
However what all these are missing is routing present in `dpSwitch` (`dpSwitchB` is `dpSwitchB = dpSwitch broadcast`) as described in `The Yampa Arcade` section 5.5.
Did I miss a function that does this somewhere? Or maybe routing isn't as useful as first thought and there are a better ways of doing it without complex switches? Thanks!

**Comment by ivanperez-keera** [comment]
This is a subissue of #40.

**Comment by ivanperez-keera** [comment]
This will be addressed as part of the new series of releases that will seek to offer 100% of Yampa's API, starting with #360 . Closing for now; a separate issue will be open to deal with that specific module or part of that module.

Thanks, @walseb !
