### ISSUE TITLE
Activate Travis caching to speedup build times?

### ISSUE THREAD

**Issue by turion** [ivanperez-keera/dunai#234]
I've recently activated caching on CI on a similar project: https://github.com/turion/essence-of-live-coding/commit/9f96218af2af974cdb40b639734fce1b31661d75
It reduced build times considerably, I think.

**Comment by ivanperez-keera** [comment]
Build times are down to 7 minutes for old GHC versions and about 3 minutes for newer ones. That's short enough. I'm not going to, for now, waste time with Travis. It may not even be a good solution long term due to its change in pricing model.

I'll close this issue, and the associated PR.

Thanks!
