### ISSUE TITLE
Bearriver: afterEachCat doesn't behave like in Yampa

### ISSUE THREAD

**Issue by walseb** [ivanperez-keera/dunai#243]
Currently `repeatedly` is defined:

``` haskell
repeatedly :: Monad m => Time -> b -> SF m a (Event b)
repeatedly q x
    | q > 0     = afterEach qxs
    | otherwise = error "bearriver: repeatedly: Non-positive period."
  where
    qxs = (q,x):qxs
```

Given `q = 1` and `x = "foo"` it feeds `afterEach` with an infinite stream of: `[(1, "foo"), (1, "foo"), (1, "foo"), (1, "foo"), ...]` because `qxs = (q,x):qxs` infinitely recurses with the same time and same event

This makes sense if the time fed to `afterEach` is relative to the last event fired. For example if `afterEach` was given `(1, "foo"), (100, "bar")`, an event would fire with `foo` at time 1 and then it schedule the next event to be fired with result `bar` at time 101. But this isn't the case, what actually happens is that `foo` fires at time 1 and `bar` fires at time 100

The problem with this is that if you have an infinite stream of `[(time, ()), (time, ()), ...]` (as the function qxs always generates), they will all fire at whatever `time` is the current time, resulting in an infinite loop. So if `time` is 10, every event in the infinite stream will fire after 10 seconds

The solutiton is to create an infinite lists where the time of the next element is `time * N`: `[(time * 1, ()), (time * 2, ()), (time * 3, ()), ...]` so that you get evenly spaced out events by time `time`. For example:
```
[(1, "foo"), (2, "foo"), (3, "foo"), (4, "foo"), ...]
```

**Comment by walseb** [comment]
I'm sorry, I see now I wasn't very concise or clear. Here is a minimal working example:
``` haskell
main = reactimate (return ()) (\ _ -> return (0.1, Just ())) (\a b -> (print b) >> pure False) sf

-- Original repeatedly definition
sf = repeatedly 1 "Iteration"

-- My changes to repeatedly
sf' =
  repeatedly' 1 "Iteration"
  where
    repeatedly' :: Monad m => Time -> b -> SF m a (Event b)
    repeatedly' q x
        | q > 0     = afterEach $ qxs q
        | otherwise = error "bearriver: repeatedly': Non-positive period."
      where
        qxs q'= (q',x):qxs (q' + q)
```

when you reactimate `sf` which is using the current definition of `repeatedly` you get:
```
NoEvent
NoEvent
NoEvent
NoEvent
NoEvent
NoEvent
NoEvent
NoEvent
NoEvent
NoEvent
Event "Iteration"
```
which stops printing after the first event because it infinitely recurses

But when you reactimate the changes to repeatedly contained in `sf'` you get:
```
NoEvent
NoEvent
NoEvent
NoEvent
NoEvent
NoEvent
NoEvent
NoEvent
NoEvent
NoEvent
Event "Iteration"
NoEvent
NoEvent
NoEvent
NoEvent
NoEvent
NoEvent
NoEvent
NoEvent
Event "Iteration"
...
```
which is how it's supposed to function as far as I know

**Comment by walseb** [comment]
As a sidenote there appears to be some strangeness going on when running my version of repeatedly with a big (for example 0.1 as above) static timestep. If you notice above, the event sometimes fires after 8 `NoEvent`, other times after 10 of them. It all seems to even out after the first few iterations but I suspect there is something strange going on with `afterEach` here

**Comment by turion** [comment]
Yes, `repeatedly` misuses the function `afterEach`. Your changes look fine, although I'd probably refactor with `scanr` and `repeat`. Something like `qxs = (, b) <$> scanr (+) 0 (repeat q)`.

> If you notice above, the event sometimes fires after 8 NoEvent, other times after 10 of them.

I don't find that surprising because the number of events depends on the sampling speed of your system, which can vary slightly over time.

**Comment by walseb** [comment]
> Yes, repeatedly misuses the function afterEach. Your changes look fine, although I'd probably refactor with scanr and repeat. Something like qxs = (, b) <$> scanr (+) 0 (repeat q).

Thanks! I will make the changes

> I don't find that surprising because the number of events depends on the sampling speed of your system, which can vary slightly over time.

I don't think that's the case because above I'm reactimating with the static time `0.1`, so it shouldn't depend on system speed right? Unless I'm misunderstanding how dunai works under the hood. Now that I think about it my problems probably arise from floating-point errors because if you add `0.1` 10 times it's unlikely you are going to get precisely `1.0` which `repeatedly` requires to return the event

**Comment by turion** [comment]
> > Yes, repeatedly misuses the function afterEach. Your changes look fine, although I'd probably refactor with scanr and repeat. Something like qxs = (, b) <$> scanr (+) 0 (repeat q).
> 
> Thanks! I will make the changes
> 
> > I don't find that surprising because the number of events depends on the sampling speed of your system, which can vary slightly over time.
> 

> I don't think that's the case because above I'm reactimating with the static time `0.1`,

Ah yes, you're right.


> Now that I think about it my problems probably arise from floating-point errors because if you add `0.1` 10 times it's unlikely you are going to get precisely `1.0` which `repeatedly` requires to return the event

True, but still the floating-point errors should be reproducible. Now I'm confused.

**Comment by ivanperez-keera** [comment]
@walseb 

There's a reason why this function is implemented this way:

https://github.com/ivanperez-keera/Yampa/blob/4aa42764ea1794f7d94967a5a7e1e769c5fdd67d/src/FRP/Yampa/EventS.hs#L156-L166

This function is literally a copy of Yampa's. If the bug exists in Yampa, then the right solution would be to first fix it there, **and then** bring it here.

Is the bug present also in Yampa?

**Comment by walseb** [comment]
I have tried this in yampa now. Yampa acts just as bearriver does after my changes. The reason why the original copied over version of repeatedly doesn't work the same in bearriver appear to be a slightly different definition of `afterEachCat`.
Yampa: https://github.com/ivanperez-keera/Yampa/blob/4aa42764ea1794f7d94967a5a7e1e769c5fdd67d/src/FRP/Yampa/EventS.hs#L216
Bearriver: https://github.com/ivanperez-keera/dunai/blob/develop/dunai-frp-bearriver/src/FRP/BearRiver.hs#L190

The difference of `afterEachCat` between the two implementations appears to stem from yampa interpreting the list `[(T1, Val1), (T2, Val2), (T3, Val3), (T4, Val4)...]` as:
```
  Event1 = T1
  Event2 = T1 + T2
  Event3 = T1 + T2 + T3
  Event4 = T1 + T2 + T3 + T4
```

So whenever the time is up in yampa, it adds on the next T. As opposed to the simpler bearriver implementation that triggers events differently:
```
  Event1 = T1
  Event2 = T2
  Event3 = T3
  Event4 = T4
```
The yampa definition of repeatedly outputs something along the lines of: `[(1, Val1), (1, Val2), (1, Val3), (1, Val4)...]`
While my updated definition of repeatedly outputs  `[(1, Val1), (2, Val2), (3, Val3), (4, Val4)...]`

Maybe I'm getting something wrong here, these functions are relatively new to me. As for what should be done, I much prefer the simpler bearriver definition. So I think it would be nicer to port it to yampa, but that would break everything relying on it which I'm guessing are quite a few projects.

**Comment by ivanperez-keera** [comment]
First of all, thanks for doing the amazing job of comparing both and figuring out what was going on.

There are two decisions to be made:
1) Should Yampa's `afterEachCat` behave differently?
2) What should BearRiver's implementation be?

The first question needs to be answer at design level at Yampa. It's an _"it this The Right™ API?"_ kind of question. It would indeed affect implementations. It would take some time to roll down.

The second question it simpler to answer: BearRiver should do whatever Yampa does. As of today, Yampa implements `afterEachCat` considering that the times are absolute, so BearRiver should too (for now). If Yampa changes its interface, BearRiver should follow.

Notice how, even though it's related, those two are independent decisions (one being "fixing" `afterEachCat`, and the other being changing something if Yampa does). If we try to take a shortcut and wait to fix BR until we can update Yampa, fix tests, adapt documentation, and change all implementations, to then roll it to BearRiver, the two could remain inconsistent for a very long time. Those kinds of shortcuts or potential optimizations are not worth it in the long run.

If making BearRiver's `afterEachCat` behave like Yampa's fixes also the issue we were trying to fix in this ticket, then this one should simple become _"`afterEachCat` in BearRiver does not behave like in Yampa_". Otherwise, we can open a separate ticket for that.

As for getting the current behaviour in BR back (if it's nicer), all you need to do is compose it with this function:

```haskell
import Data.Foldable (foldl')

makeTimesRelative :: Num t => [(t, b)] -> [(t, b)]
makeTimesRelative = reverse . snd . foldl step (0, [])
  where
    step :: Num t => (t, [(t, b)]) -> (t, b) -> (t, [(t, b)])
    step (t0, xs) (t, x) = (t, (t - t0, x) : xs)
```
Notice that `foldl` is known to be inefficient sometimes, so you may want to play with `foldl'` or other folds.

BearRiver's current `afterEachCat` could still be "obtained" as:

```haskell
relativeAfterEachCat = Yampa.afterEachCat . makeTimesRelative
```

I would suggest, for now, adding that locally to your programs as you need it. The decision of making this part of Yampa can be revisited in the future in Yampa. There's a chance that there's a historical reason behind the current behaviour (I don't know if that's the case now but it has been before) .

**Comment by ivanperez-keera** [comment]
As an addendum, and conversely to what I wrote above to implement `relativeAfterEachCat`, there's a relatively simple way of getting Yampa's behaviour in BR, which is to precompose the current implementation with the following function:

```
makeTimesAbsolute :: Num t => [(t, b)] -> [(t, b)]
makeTimesAbsolute = reverse . snd . foldl step (0, [])
  where
    step :: Num t => (t, [(t, b)]) -> (t, b) -> (t, [(t, b)])
    step (t0, xs) (t, x) = (t + t0, (t + t0, x) : xs)
```

However:
- The same considerations regarding `foldl` apply.
- This implementation would not work for infinite lists (does `Yampa.afterEachCat` work with infinite lists?).
- It's possible that it would be simpler to adapt the current code than to add more code.

Notice how the value of the first pair in the accumulator in step goes from `t` in `makeTimesRelative` to `t + t0` in `makeTimesAbsolute`.

**Comment by ivanperez-keera** [comment]
@walseb What do you think?

**Comment by walseb** [comment]
@ivanperez-keera Ah sorry! I will look over this in more detail over the weekend. But making the time transform higher order using some kind of fold as you suggested seems like the best and most flexible solution. Great work!

**Comment by ivanperez-keera** [comment]
Thanks for the quick reply :) Ok, no worries. Let's wait until the weekend then so you have more time to look at it in detail.

**Comment by walseb** [comment]
I've had more time to look into this now. Making use of your `makeTimesAbsolute` won't work sadly because `repeatedly` sends an infinite list to `afterEachCat` by design (because it never terminates). But couldn't you use `scanl` in the definition instead of `foldl`? That should make it work with infinite lists I believe. 

`afterEachCat` is indeed the problem and `repeatedly` would work properly if `afterEachCat` was changed to behave like in Yampa. I will rename this issue.

I don't see any reasonable alternative but to modify `afterEachCat` in BR to behave like yampa in the short term. After that it's an API question as you say. I prefer the simpler implementation which is to use absolute time in the time list but that would probably break many things to probably limited benefit. It might be better to instead let anyone who needs it introduce `afterEachCatAbs` instead.

**Comment by ivanperez-keera** [comment]
Ok, for now, let's modify `afterEachCat` to behave like in Yampa.

There are a few changes coming to both libraries that, hopefully, will make it easier to evaluate the impact of API decisions. So, I expect there'll be a chance to re-evaluate this in the future.

Would you like to try to do it, or do you want me to take on this one?

**Comment by walseb** [comment]
Cool! I'm willing to give it a go but it might take a week. I'm unexpectedly deprived of my computer this weekend. Great job with the benchmarks! I'm looking forward to them being introduced as I have little understanding of FRP specific performance issues.

**Comment by ivanperez-keera** [comment]
Great! A week would be fine. If we manage to fix it by then, we might make it to the next milestone: https://github.com/ivanperez-keera/dunai/milestone/9

**Comment by walseb** [comment]
@ivanperez-keera Done! https://github.com/ivanperez-keera/dunai/pull/260

**Comment by ivanperez-keera** [comment]
@walseb Before merging, I wanted to make sure all was working and it turns out I found a mistake in the code. My goal was to check that it behaved like Yampa's `afterEachCat`, but it turns out the function is just not total so it crashes.

Here's the code I used:

```haskell
{-# LANGUAGE PackageImports #-}

import Data.Functor.Identity
import Test.QuickCheck

import             FRP.Dunai.Stream     as Dunai
import "bearriver" FRP.Yampa            as BearRiver
import "Yampa"     FRP.Yampa            as Yampa
import             FRP.Yampa.Stream     as Yampa
import             FRP.Yampa.QuickCheck as Yampa

main :: IO ()
main = quickCheck $
       forAll Yampa.uniDistStream $ \inputStream ->
       forAll Yampa.uniDistStream $ \afterEachCatStream ->
       property $ bisimulation (sfY afterEachCatStream) (sfBR afterEachCatStream) inputStream

     where
       sfY :: Yampa.SignalSampleStream Double -> Yampa.SF Double (Yampa.Event [Double])
       sfY st = Yampa.afterEachCat (snd st)

       -- Same SF using bearriver. We convert the Event result type to Yampa.
       -- We can use Yampa's SSS type because it's all implemented with type synonyms
       -- and the implementations coincide.
       sfBR :: Yampa.SignalSampleStream Double -> BearRiver.SF Double (Yampa.Event [Double])
       sfBR st = BearRiver.afterEachCat (snd st) >>> arr brEventToYampa

yampaStreamToDunai :: Yampa.SignalSampleStream a -> Dunai.SignalSampleStream a
yampaStreamToDunai (x, xs) = (0, x) : xs

bisimulation :: Eq b
             => Yampa.SF a b
             -> BearRiver.SF a b
             -> Yampa.SignalSampleStream a
             -> Bool
bisimulation yampaSF brSF sss =
    map snd (yampaStreamToDunai sssY') == sssBR'
  where
    (sssY', _)  = Yampa.evalSF yampaSF sss
    (sssBR', _) = runIdentity $ Dunai.evalSF brSF (yampaStreamToDunai sss)

-- | Convert from BearRiver event to Yampa event.
-- Needed to compare events using equality.    
brEventToYampa :: BearRiver.Event a -> Yampa.Event a
brEventToYampa (BearRiver.Event x) = Yampa.Event x
brEventToYampa BearRiver.NoEvent   = Yampa.NoEvent
```

**Comment by walseb** [comment]
Interesting! That's the very scenario I said I thought was impossible in the PR. I will take a look and attempt a fix later this week. Many thanks for putting in the effort of testing it properly!

**Comment by ivanperez-keera** [comment]
Of course!

I'm planning to release this Thursday, but I imagine you may be too busy before the weekend, which is understandable. Just letting you know so you are aware, nothing more.

The strategy above could make for a interesting way of testing Yampa and BearRiver for equivalence. It could potentially serve as the basis for a battery of tests that accompanies BearRiver.
