### ISSUE TITLE
README contains old installation instructions

### ISSUE THREAD

**Issue by ivanperez-keera** [ivanperez-keera/dunai#253]
### Reasoning

The `README.md` currently suggest installation instructions that are not up to date with current versions of Haskell development tools. In particular, they suggest using `cabal sandbox`, a command that is no longer supported (cabal-install-3.2 supports v1-sandbox, but that command has also gone away in more recent versions of cabal-install).

### Solution

The `README.md` file needs to be updated to reflect a current installation procedure with cabal (at least cabal-install 3.4 or even 3.6).

### Procedure

- Modify the `README.md` file to update the installation instructions to work with a recent version of cabal. Please note that there are installation instructions (which contain the outdated `cabal sandbox init`) at least twice. Make sure the instructions work in Cabal 3.4 (or even 3.6).
- Commit with the following message:
 ```
Update installation instructions in README. Refs #<this-issue-number>.

The README suggests installation instructions that are not up to date with
current versions of Haskell development tools. In particular, they suggest
using `cabal sandbox`, a command that is no longer supported.

This commit modifies the README to provide up-to-date installation
instructions, tested with cabal-install <cabal-install-version-number-you-tried>

[ci skip]
```

### Notes
- This is a great candidate issue for someone who wants to contribute to an open source library.
- The first line gives a simple, one-line summary. The Refs at the end gives a quick link to this issue without having to go into the commit. Do not use `fix` or `close` followed by the issue number: we'll use that in the commit message of the merge.
- The long description documents the issue. It also helps others review the change and understand both the reasoning and your tests, if they need to replicate the status.
- The `[ci skip]` at the end makes travis not re-compile dunai with this change: because it touches the `README.md` file only, the code has not changed and it will continue to compile and pass all tests if it did before.

You can modify that message if you think other information is relevant or helpful, but please keep a similar structure.

**Comment by DireWolf707** [comment]
I am new to open source and want to contribute. Can you assign this issue to me?

**Comment by ivanperez-keera** [comment]
Thanks! Done.

**Comment by ivanperez-keera** [comment]
@DireWolf707 Are you able to do this one too? This one will be a tiny bit harder, but it's more important too :)

**Comment by ivanperez-keera** [comment]
Thanks @DireWolf707. Almost there! I left a couple of comments the PR. When you have a chance, please take a look.
