### ISSUE TITLE
URLs in travis badge point to old travis-ci.org website

### ISSUE THREAD

**Issue by ivanperez-keera** [ivanperez-keera/dunai#254]
### Reasoning

The service Travis CI is migrating  open source projects from travis-ci.org to travis-ci.com. Dunai has been migrated among them.

The README.md contains a badge at the top that includes the build status of this project. At present, that badge points to the old location on travis-ci.org. The image is still shown correctly, but the link to the CI page is broken. Both should be updated.

### Solution

The image and destination URLs in the Travis badge at the top of the `README.md` file need to be updated to point to the corresponding paths on travis-ci.com.

### Procedure

- Modify the `README.md` file to update the URLs. Check that the new URLs exist (a simple substitution of the domain name will not do).
- Commit with the following message:
 ```
Update Travis CI badge URLs in README. Refs #<this-issue-number>.

The service Travis CI is migrating open source projects from travis-ci.org to
travis-ci.com. Dunai has been migrated among them.

The README.md contains a badge at the top that includes the build status of
dunai. At present, that badge points to the old location on travis-ci.org. The
image is still shown correctly, but the link to the CI page is broken. Both
should be updated.

This commit updates both URLs to point to their new locations under the
travis-ci.com domain.

[ci skip]
```

### Notes
- This is a great candidate issue for someone who wants to contribute to an open source library.
- The first line gives a simple, one-line summary. The Refs at the end gives a quick link to this issue without having to go into the commit. Do not use `fix` or `close` followed by the issue number: we'll use that in the commit message of the merge.
- The long description documents the issue and helps others review the change and understand both the reasoning and your solution.
- The `[ci skip]` at the end makes the CI server not re-compile dunai with this change: because it touches the `README.md` file only, the code has not changed and it will continue to compile and pass all tests if it did before.

You can modify that message if you think other information is relevant or helpful, but please keep a similar structure.

**Comment by DireWolf707** [comment]
I am new to open source and want to contribute. Can you assign this issue to me?

**Comment by ivanperez-keera** [comment]
Thanks! Done.

**Comment by ivanperez-keera** [comment]
@DireWolf707 any luck?

**Comment by DireWolf707** [comment]
Sry for delay. Please check and suggest changes if any.

**Comment by ivanperez-keera** [comment]
No problem! Nicely done!
