### ISSUE TITLE
Update email address in cabal packages

### ISSUE THREAD

**Issue by ivanperez-keera** [ivanperez-keera/dunai#264]
The email address in all the cabal packages is outdated.

It should point to a new address, ideally something that does not disclose my personal email address (TBD).

**Comment by modotte** [comment]
Hello. I encountered this project at random and also I noticed the date sets back to several months ago. To save whoever's time that is going to send the PR, here's a simple bash code to replace all current maintainer's email address with a different one.

```bash
for i in $(find -name *.cabal); do
    # Make sure to prepend 3 additional spaces for new address.
    # This will ensure indentation consistency.
    gawk -i inplace '{ sub("ivan.perez@keera.co.uk", "   new@email.com", $2); print }' "$i"
done
```

**Comment by ivanperez-keera** [comment]
Thank you all. There has been a change of plans.

It seems that this will no longer be necessary. Sorry for the noise.
