### ISSUE TITLE
Arrow transformer instances

### ISSUE THREAD

**Issue by turion** [ivanperez-keera/dunai#29]
In order to connect to existing code, we should have instances for `ArrowReader` etc. from https://hackage.haskell.org/package/arrows
This would also make certain constructions easier, since one often has several transformers in the monad stack, and `arrows` has type classes like `mtl` does.

**Comment by turion** [comment]
`arrow` doesn't have type classes that correspond exactly to our `MaybeT` and `ExceptT`, probably because they can't be emulated in an obvious way with newtypes like the corresponding `ReaderT` classes. They should be created.

**Comment by ivanperez-keera** [comment]
I'm not going to work on this any time soon, probably, unless I find the need in a game. So, if you want to give it a try, go ahead.

**Comment by turion** [comment]
I experimented a bit with this, but it seems that the arrow transformers as they are in the `arrow` package are not really what we're after. I thought that they are useful to access side effects that are buried under a monad stack, i.e. accessing `ask` inside an `MSF (t1 (t2 (... ReaderT r m))) a b`, like `mtl` does. But in fact, you can already achieve this by just using `mtl` (dunai doesn't even need to depend on `mtl`) like this:

```
arrM_ ask :: MonadReader r m => MSF m () r
```

The only other interesting thing might be capturing our wrapping/running functions in type classes, and see whether we can wrap and run under additional transformers, i.e. `runReaderS :: MSF (t (ReaderT r m)) a b -> MSF (t m) (a, r) b`. But that's a separate issue.
