### ISSUE TITLE
`dunai`: instance of `VectorSpace` does not implement `dot`

### ISSUE THREAD

**Issue by ivanperez-keera** [ivanperez-keera/dunai#298]
The MSF instance of `VectorSpace` does not give an implementation for `dot`:
```
src/Data/MonadicStreamFunction/Instances/VectorSpace.hs:46:10: warning: [-Wmissing-methods]
    • No explicit implementation for
        ‘dot’
    • In the instance declaration for ‘VectorSpace (MSF m a v) s’
   |
46 | instance (Monad m, VectorSpace v s) => VectorSpace (MSF m a v) s where
```

This is tricky, since the function is supposed to return a scalar, not an `MSF` of a scalar.

Perhaps the instance of `VectorSpace` should be:
```haskell
instance (Monad m, VectorSpace v s) => VectorSpace (MSF m a v) (MSF m a s) where
```

It is the last warning that dunai gives during compilation. If we manage to get rid of it (correctly), then dunai will be 100% warning-free.

**Comment by ivanperez-keera** [comment]
It is possible to "make it work" by making a change to `simple-affine-space`, `bearriver`, and `Yampa`. The following implementation compiles in dunai when those changes are made:
```haskell
-- | Vector-space instance for 'MSF's.
instance (Eq s, Floating s, Monad m, VectorSpace v s) =>
    VectorSpace (MSF m a v) (MSF m a s)
  where
    zeroVector   = constantly zeroVector
    (*^)         = elementwise2 (*^)
    (^/)         = elementwise2 (^/)
    (^+^)        = elementwise2 (^+^)
    (^-^)        = elementwise2 (^-^)
    negateVector = (>>^ negateVector)
    dot          = elementwise2 dot
    normalize v  = elementwise2 f v (norm v)
        where
          f v' nv'
            | nv' /= 0  = v' ^/ nv'
            | otherwise = error "normalize: zero vector"
```

**Comment by ivanperez-keera** [comment]
Yampa just had a new release that makes sets explicit constraints on the versions of simple-affine-space, making the transition to this implementation easier.

**Comment by ivanperez-keera** [comment]
@turion What do you think of implementing that instance this way instead? https://github.com/ivanperez-keera/dunai/issues/298#issuecomment-1146666030

Note that it's overlapping with the exiting one. The plan would be to take the current one would go away and use https://github.com/ivanperez-keera/dunai/issues/298#issuecomment-1146666030 instead.

**Comment by ivanperez-keera** [comment]
Note: issue #339 implemented simple-affine-space support (irrespective of what we decide to do here).

**Comment by turion** [comment]
It's mathematically sound I believe, but one looses a bit of expressive power. One can still write `3 *^ myMSF` because `Num s => Num (MSF m a s)`, but to multiply with a variable of type `s` one then needs to use `constantly` (or arrow expressions).

**Comment by turion** [comment]
I think the trouble really stems from the fact that `VectorSpace` 1. has functional dependencies onto the scalar type 2. includes `dot` and `norm`, both of which are not part of the definition of a vector space. We had that discussion before I believe, and I proposed a more precise `VectorSpace < InnerProductSpace < MetricSpace` hierarchy`, but it may be overkill for the use case.

Given that we will probably not touch the definition of `VectorSpace`, your proposal sounds like a great one! Maybe one can add to the Haddocks for `Num (MSF m a s)` that it is therefore possible to use numeric literals as `MSF`s (maybe also in other parts of the documentation), because that's something that beginners will often not know.

**Comment by ivanperez-keera** [comment]
@turion I've just pushed my suggested changes to a branch (https://github.com/ivanperez-keera/dunai/tree/develop-dot). My plan is to merge this in the next release (coming out on Feb 21st).

Could you help me make the changes to the documentation more concrete? What documentation of what module(s) do you think should change, and how?

**Comment by turion** [comment]
https://github.com/ivanperez-keera/dunai/commit/19a502f980021e82a1abd4e39ad193a042b36cce#diff-1f46224b21d671e0759360bc9e30aaff81008c17e5639b93621231fc2f60fe1eR60

This I find a bit problematic, I'd prefer an `MSF` that returns `v ^* Infinity` all the time (where `v` is the unnormalized vector, and `1/0 = Infinity`). That way, the error can be contained locally, while an `error` always bubbles up to the top level. (I'm aware that this is different than the Yampa and bearriver implementation.)

> Could you help me make the changes to the documentation more concrete? What documentation of what module(s) do you think should change, and how?

I think the `Num s => Num (MSF m a s)` instance should have an example that one can use number literals to define `MSF`s, and the vector space instance should have an example that one can multiply an `MSF` by a number literal.

**Comment by ivanperez-keera** [comment]
> This I find a bit problematic, I'd prefer an MSF that returns v ^* Infinity all the time (where v is the unnormalized vector, and 1/0 = Infinity).

I think then that that would be the same as defining:
```haskell
normalize v  = v ^/ (norm v)
```

> That way, the error can be contained locally,
 
There are ways but it is hackish. I agree that, if the function is partial, a better way to represent that is needed.

> (I'm aware that this is different than the Yampa and bearriver implementation.)

Indeed, that behavior comes from `simple-affine-space`. The right way would be to "flow it down" from there.

> I think the Num s => Num (MSF m a s) instance should have an example that one can use number literals to define MSFs, and the vector space instance should have an example that one can multiply an MSF by a number literal.

Ok. This is now merged and released, so we can file that separately as a proposed improvement.
