### ISSUE TITLE
Weaker reactimate signature in BearRiver

### ISSUE THREAD

**Issue by mkm0815** [ivanperez-keera/dunai#3]
Hi all,
I would propose changing the signature from reactimate to the one used in the develop branch of the Yampa repo.
That would encurage people (like myself) that use Yampa from the devlop branch to switch to BearRiver

the new signature of reactimate would be:
`reactimate :: Monad m a => (Bool -> m (DTime, Maybe a)) -> (Bool -> b -> m Bool) -> SF Identity a b -> m ()`

**Comment by ivanperez-keera** [comment]
This could be added to bearriver. I'm happy to accept this as a pull request. Could you please send a patch?
