### ISSUE TITLE
`bearriver`: haddock code docs missing from Yampa

### ISSUE THREAD

**Issue by geroldmeisinger** [ivanperez-keera/dunai#323]
Subissue of #40 .

EDIT: Ivan Perez: Relate to parent issue.

**Comment by ivanperez-keera** [comment]
As we copy stuff from Yampa, there's a potential legal issue that we need to clarify. Yampa is (c) Henrik Nilsson and Antony Courtney (when they were at Yale). Dunai is (c) me and Manuel Baerenz.

Most likely, do not hold the same copyright owners, but if we start copying from Yampa and don't sort this out, it'll be much harder in the future.

**Comment by geroldmeisinger** [comment]
https://hackage.haskell.org/package/Yampa-0.9.1.1 => BSD-3, which is permissive (unless the uploader made this up(?))

**Comment by ivanperez-keera** [comment]
Sure, but the fact that we are allowed to copy (under certain terms) doesn't mean that we can misrepresent authorship or not list the original copyright holders of those portions.

**Comment by ivanperez-keera** [comment]
And no, the uploader didn't "make it up". The license of Yampa is BSD.

**Comment by ivanperez-keera** [comment]
I've written to Henrik Nilsson and Antony Courtney to discuss this issue.

**Comment by geroldmeisinger** [comment]
According to [Wikipedia](https://en.wikipedia.org/wiki/BSD_licenses) there originally was a "4-clause BSD licence" which included a "advertising clause" that:

> required authors of all works deriving from a BSD-licensed work to include an acknowledgment of the original source in all advertising material.
> every occurrence of the license with a different name required a separate acknowledgment. 

In the new "3-clause BSD" licence this was specificly dropped.

According to http://www.linfo.org/bsdlicense.html:

> people who made changes to the source code often wanted to have their names added to the acknowledgment. This could easily result in large and cumbersome acknowledgments for products with numerous contributors and for software distributions consisting of multiple individual projects. 
> if an operating system or other program required fifty slightly different acknowledgment sentences, each naming a different developer or group of developers, such advertising alone might require a full page.

**Comment by ivanperez-keera** [comment]
It's a bit more complicated than that. Most likely, about 75% of bearriver will be almost equal if not exactly equal to Yampa (and may one day become the implementation of Yampa).

In some form, I've touched pretty much every line in the Yampa code (some more, some less), but I'm neither listed as an author nor hold, according to the license, any copyright ownership. Let's see what the Yampa authors say and take it from there.

**Comment by ivanperez-keera** [comment]
From the message I sent:

> Bearriver was born as a separate library, hence the original copyright statement only mentioning me and Manuel. As time went on, it's borrowed more and more from Yampa. So far it's been mostly API, although some code is the same in both libraries. The expectation is that more will be shared between the two (could easily end up being 60%-80% of the code). Regardless of how we get to that point, the line between the two will be blurred, which begs the question of whether this is "our" library (Manuel and mine's) with some hints of Yampa, or is this really a fork of Yampa that should be in great part also attributed to [Antony and Henrik].

**Comment by geroldmeisinger** [comment]
from a moral point of view I think they should be credited: it's great work!
from a legal point of view I think copyright doesn't require any name to be mentioned at all. there could be a third author who may claim additional rights anytime (e.g. what about Hudak's contributions and the will of his heirs?). if BSD3 holds, because we believe Antony and Henrik are they sole authors and they actually used BSD3, we don't need to (legally) mention them. anyone creating a fork of Yampa can claim is at his/hers as much as they want, which doesn't effect the actual (legal) authorship in any way. if we used only 1% then Yampa's licence applies already, which pretty much states: do want you want, but you cannot change the licence.

**Comment by ivanperez-keera** [comment]
Just confirming that I received a response and I should be able to move forward with this soon. There'll be a small change pertaining to the licenses in both projects (just naming owners and years, etc.) and that'll unlock this issue.
