### ISSUE TITLE
add missing Event instances from Maybe

### ISSUE THREAD

**Issue by geroldmeisinger** [ivanperez-keera/dunai#327]
Yampa provides: `Show (via deriving), Eq, Ord, Functor, Applicative, Monad, Fail.Monad.Fail, Alternative, NFData(?)`
missing in Yampa compared to PR: `Semigroup, MonadPlus, MonadFix, MonadFail (standard?), Foldable, Traversable, MonadZip, (Eq1, Ord1, Show1)`

related to issue #212, #326

**Comment by ivanperez-keera** [comment]
The place for these would be in Yampa. Bearriver will implement the Yampa API. This needs to be changed in Yampa (if there is a real use case for it), and, if so, then it becomes a subissue of #40 in this repo.
