### ISSUE TITLE
`dunai`: Use Safe Haskell

### ISSUE THREAD

**Issue by geroldmeisinger** [ivanperez-keera/dunai#330]
> Multiple FRP libraries ... often using weak references and an IO monad behind the scenes. Additional measures must be taken to guarantee referential transparency and efficient garbage collection in the presence of non-commutative monads like IO. These frameworks also include combinators to connect signals or event streams to external sources and sinks, which also requires IO. This is a pragmatic choice, but the drawback is that the IO connection is not shown explicitly in the type. The manifest reflection of all effects in the types is a strength of the proposed abstraction framework. For example, for pure MSFs without IO we can perform reproducible tests using automated testing tools like QuickCheck [118], and obtain more guarantees than in IO-based FRP implementations.

As such, shouldn't we also mark it `Safe`?

It seems to work without major changes except for `Parallel` because of `import GHC.Conc      (par, pseq)` which is specifically marked as `Unsafe`, but could be inlined. [GHC.Conc](https://hackage.haskell.org/package/base-4.16.1.0/docs/src/GHC-Conc-Sync.html)

**Comment by geroldmeisinger** [comment]
(how do you add tags to the issue and monospace in title?)

**Comment by ivanperez-keera** [comment]
For monospace, use \`this syntax\`. For tags (labels), only the admins can add them.

**Comment by ivanperez-keera** [comment]
> shouldn't we also mark it Safe?

I'm not sure that we should. Based on what you are saying, it seems that we could.

I'll turn the question around: should we and, if so, why?

**Comment by geroldmeisinger** [comment]
https://wiki.haskell.org/Safe_Haskell
> it "hardens" the Haskell language by providing five properties: type safety, referential transparency, strict module encapsulation, modular reasoning, semantic consistency.
> For typical Haskell programmers, using `{-# LANGUAGE Safe #-}` will be like `-Wall`: something that is considered good practice from a hygiene point of view. If you don't need access to unsafe features, then it's better to write in the safe subset, where you have stronger guarantees.

=> it already is `safe`, dunai is "advertised" as such, so why not put the `safe` tag on it and increase the trust in the module plus make sure any chances are guaranteed to keep this promise.

**Comment by ivanperez-keera** [comment]
I understand what it does. It's unclear to me that:
- It really increases trust. (See for example: https://twitter.com/TomSmeding/status/1566424745784053760).
- That people care in practice. Are people really relying on safe haskell?

We are doing it for a different project that I'm in, but it's also the only project I'm using it in.

I had to request a change in a dependency to mark two functions as trustworthy from an otherwise unsafe module. A solution I liked was to isolate those two functions in their own module, which is itself marked as trustworthy, and then re-export them. What I liked about that is that it limited the possible errors to only those two functions, but we didn't have to copy them over.

**Comment by geroldmeisinger** [comment]
https://downloads.haskell.org/ghc/latest/docs/users_guide/exts/safe_haskell.html

Downsides: disables TemplateHaskell and restrictes: ForeignFunctionInterface, Rules (were used in Yampa and this would have an performance impact), OverlappingInstances, GeneralisedNewtypeDeriving, DerivingVia, GHC.Generics
but non of these are used in dunai

some people say it's a pain to maintain and not really used much

**Comment by ivanperez-keera** [comment]
Maybe for these reasons, I don't think we need to burden us with this decision right now. Most modules are safe-inferred (except for one?), and for the people that care, that will likely suffice.

There are plenty of issues in Yampa and dunai that have much higher priority, and that's what I prefer to put my energy into at this point.
