### ISSUE TITLE
Missing export SF in FRP.Yampa in BearRiver

### ISSUE THREAD

**Issue by mkm0815** [ivanperez-keera/dunai#4]
Hi all,
SF is not exported from FRP.Yampa in BearRiver.
So no Yampa source will compile with BearRiver

**Comment by ivanperez-keera** [comment]
This is strange. I have example that work. These were even used for the paper. Maybe I just forgot to push.

Can you please send a pull request?

**Comment by ivanperez-keera** [comment]
This is definitely exported by the FRP.Yampa module inside examples/bearriver/src/. Please, re-open or file a new issue if the problem persists.
