### ISSUE TITLE
Upgrade transformers to 0.6.x

### ISSUE THREAD

**Issue by nullobject** [ivanperez-keera/dunai#413]
It would be great to update the `transformers` dependency to 0.6.x. Having such an old version makes dunai a pain to integrate into a modern project.

I understand this is because the `ListT` transformer is still being used in the `Control.Monad.Trans.MSF.List` module.

Is it possible to get `ListT` from somewhere else, now that it has been removed from `transformers`?

**Comment by ivanperez-keera** [comment]
We are almost there.

You may want to follow https://github.com/ivanperez-keera/dunai/discussions/368. There's been recent updates.

You should be able to use this branch for now https://github.com/ivanperez-keera/dunai/tree/develop-list-transformer and bump the major on that dependency manually in the cabal file.

**Comment by ivanperez-keera** [comment]
Sorry, you may also need to remove the old List module from a few place, or just replace it with the alternative provided. It's WIP. But as I said, almost there.

**Comment by nullobject** [comment]
That's great news, thanks for the update @ivanperez-keera .

I'll close this issue and keep my :eyes: on the WIP.
