### ISSUE TITLE
The `catchM` function in the paper is missing

### ISSUE THREAD

**Issue by nullobject** [ivanperez-keera/dunai#414]
The paper describes the `catchM` function in the "Exceptions and Control Flow" section, which I assume refers to the `catchMaybe` function in the library.

Should the sample code in the paper be updated to use the correct function?

**Comment by ivanperez-keera** [comment]
Hi @nullobject .

We keep a copy of the examples in the paper here: https://github.com/ivanperez-keera/dunai/blob/develop/dunai-examples/paper/src/

I believe that'd fall under https://github.com/ivanperez-keera/dunai/blob/develop/dunai-examples/paper/src/DunaiExamplesMonads.hs.

Are those working? Or did you mean a different example that is not in that directory?

**Comment by nullobject** [comment]
Ah, it was in this LHS file I saw it: https://github.com/ivanperez-keera/dunai/blob/21eff0fd159c49aed0588942fedc8cfe70f27c93/dunai-examples/paper/src/monads.lhs#L174

**Comment by ivanperez-keera** [comment]
Since the comment lists the function, it's just been renamed, I'm going to close this. If something needs to be changed, please re-open.
