### ISSUE TITLE
hackage documentation is missing?

### ISSUE THREAD

**Issue by madjestic** [ivanperez-keera/dunai#415]
When pressing `s` while `https://hackage.haskell.org/package/dunai` is open in a browser window, the documentation navigation menu does not show up.  Was documentation generated with haddock and uploaded?

Regards,
Vlad

**Comment by ivanperez-keera** [comment]
It's a bit strange because if you go to https://hackage.haskell.org/package/dunai-0.12.3/docs/Control-Monad-Trans-MSF.html and press `s` then search works.

I don't think we did anything differently in the last release.

**Comment by madjestic** [comment]
it is strange indeed, but thanks for pointing out that it works otherwise!
