### ISSUE TITLE
`dunai`: Failure to build with `transformers-0.6`

### ISSUE THREAD

**Issue by tomsmeding** [ivanperez-keera/dunai#427]
It seems the transformers-0.6 support in dunai 0.13 (following discussion https://github.com/ivanperez-keera/dunai/discussions/368) does not yet work correctly. The problem is that dunai [unconditionally depends on `transformers < 0.6`](https://github.com/ivanperez-keera/dunai/blob/1918c1b3388c4680edb1129e0732e1db1f1d8e93/dunai/dunai.cabal#L136) and, if the `list-transformer` flag is set, [additionally depends on `transformers < 0.7`](https://github.com/ivanperez-keera/dunai/blob/1918c1b3388c4680edb1129e0732e1db1f1d8e93/dunai/dunai.cabal#L157) -- the constraints are conjunctive, so dunai _always_ has an upper bound of 0.6 on transformers.

Furthermore, the `mtl < 2.3` constraint on bearriver also excludes transformers-0.6; one needs mtl >= 2.3 to use transformers-0.6.

A good way to test this is:
```
$ cabal build dunai -c 'transformers >= 0.6'
```
which currently gives (cabal 3.12):
```
Resolving dependencies...
Error: [Cabal-7107]
Could not resolve dependencies:
[__0] trying: bearriver-0.14.9 (user goal)
[__1] next goal: transformers (dependency of bearriver)
[__1] rejecting: transformers-0.5.6.2/installed-0.5.6.2 (constraint from command line flag requires >=0.6)
[__1] trying: transformers-0.6.1.1
[__2] next goal: mtl (dependency of bearriver)
[__2] rejecting: mtl-2.2.2/installed-2.2.2 (conflict: transformers==0.6.1.1, mtl => transformers==0.5.6.2/installed-0.5.6.2)
[__2] rejecting: mtl-2.3.1 (conflict: bearriver => mtl>=2.1.2 && <2.3)
[__2] rejecting: mtl-2.2.2 (conflict: transformers==0.6.1.1, mtl => transformers>=0.4 && <0.6)
[__2] skipping: mtl; 2.2.1, 2.2.0.1, 2.2, 2.1.3.1, 2.1.2, 2.1.1, 2.0.1.1, 2.0.1.0, 2.0.0.0 (has the same characteristics that caused the previous version to fail: excludes 'transformers' version 0.6.1.1)
[__2] rejecting: mtl-1.1.1.1 (conflict: bearriver => mtl>=2.1.2 && <2.3)
[__2] skipping: mtl; 1.1.1.0, 1.1.0.2, 1.1.0.1, 1.1.0.0, 1.0, 2.3, 2.1 (has the same characteristics that caused the previous version to fail: excluded by constraint '>=2.1.2 && <2.3' from 'bearriver')
[__2] fail (backjumping, conflict set: bearriver, mtl, transformers)
After searching the rest of the dependency tree exhaustively, these were the goals I've had most trouble fulfilling: mtl, transformers, bearriver
```

**Comment by ivanperez-keera** [comment]
Hi Tom. Would you be able to send a pull request?

Thanks!
