### ISSUE TITLE
Increase bounds on dependencies

### ISSUE THREAD

**Issue by ivanperez-keera** [ivanperez-keera/dunai#436]
`bearriver` specifies a version bound `MonadRandom < 0.6`, but that could potentially be relaxed to `< 0.7`.

`dunai-test` specifies a version bound `QuickCheck < 2.15`, but it could potentially be relaxed to `< 2.16`.

**Comment by ivanperez-keera** [comment]
If someone wants to do this, please go ahead and send a PR.

Please create 4 commits:
- Commit 1: relax version bounds on `MonadRandom` in `bearriver`.
- Commit 2: relax version bounds on `QuickCheck` in `dunai-test`.
- Commit 3: Update `bearriver`'s changelog.
- Commit 4: Update `dunai-test`'s changelog.

**Comment by pbrinkmeier** [comment]
I opened a PR for this.

**Comment by ivanperez-keera** [comment]
Thank you so much for your contribution, @pbrinkmeier . It's been merged now.
