### ISSUE TITLE
`bearriver`: `loopPre` is defined twice

### ISSUE THREAD

**Issue by ivanperez-keera** [ivanperez-keera/dunai#438]
The function `loopPre` is defined twice: once in `FRP.BearRiver`, and once in `FRP.BearRiver.Loop`. Only one definition should be needed.

This prevents `FRP.BearRiver` from providing an API equivalent to Yampa's.

**Comment by ivanperez-keera** [comment]
My intuition here would be to just remove the one in `FRP.BearRiver`.

**Comment by pbrinkmeier** [comment]
Hi, I'd like to work on this issue. The second approach seems less likely to break the API, so I would perhaps go with that?

**Comment by ivanperez-keera** [comment]
Great!

Yeah, let's go with the second approach. Can you please structure it this way?

- Commit 1: Expose FRP.Yampa.Loop in FRP.Yampa hiding FRP.BearRiver.loopPre
- Commit 2: Document changes in CHANGELOG.

Always reference the issue with `. Refs #438.` at the end of the commit message summary, etc.

I need to have the next release ready tonight (EOB Pacific time). Do you think you can have it ready for then?

**Comment by pbrinkmeier** [comment]
I applied the changes in #441. The duplicate definition of `loopPre` is removed and replaced by re-exports where required. Please check if I understood the task, then I will add a changelog entry.

**Comment by ivanperez-keera** [comment]
Thanks! I responded in the PR.
