### ISSUE TITLE
`dunai-test`: Remove deprecated functions

### ISSUE THREAD

**Issue by ivanperez-keera** [ivanperez-keera/dunai#444]
`dunai-test` includes several deprecated definitions that were deprecated a year ago (see #385). They can safely be removed.

**Comment by ivanperez-keera** [comment]
If someone wants to do this, please go ahead and send a PR.

Please create 2 commits:
- Commit 1: Remove all deprecated definitions from `dunai-test/src/FRP/Dunai/LTLPast.hs`.
- Commit 4: Update `dunai-test`'s changelog.

Please check out the recent history of this repository to see how we normally document commits, and how we link commits to issues in the subject line of the commit messages.

**Comment by solomon-b** [comment]
What about the deprecations in `Control.Monad.Trans.MSF.List`?

**Comment by ivanperez-keera** [comment]
Hi @solomon-b . I opened a separate issue to deal with those: https://github.com/ivanperez-keera/dunai/issues/445

Those should be in separate PRs. Thanks!
