### ISSUE TITLE
`bearriver`: the function `reactimate` is API-incompatible

### ISSUE THREAD

**Issue by ivanperez-keera** [ivanperez-keera/dunai#454]
The function `reactimate` doesn't have the same signature as in Yampa: in `bearriver` it forces the monad of the SF to be the same as the monad of the sensing/actimation actions and reactimate itself, but a Yampa SF is mapped to a Bearriver SF on the Identity monad.

This makes modules that use Yampa's `reactimate` not API-compatible with bearriver.

Bearriver's `FRP.Yampa` module should hide `FRP.BearRiver.reactimate` and define one in `FRP.Yampa` that has the same signature as Yampa's (likely relying on `FRP.BearRiver.reactimate` via a qualified import).

**Comment by ivanperez-keera** [comment]
If someone wants to do this, please go ahead and send a PR.

Please create 2 commits:
- Commit 1: Hide `reactimate` in the unqualified import of `FRP.Bearriver` in `FRP.Yampa` (https://github.com/ivanperez-keera/dunai/blob/develop/dunai-frp-bearriver/src/FRP/Yampa.hs#L12). Introduce a new `reactimate` in `bearriver`'s `FRP.Yampa` module that has the same signature as `Yampa`'s. Implement it as needed. See `dunai`'s `morphS` and rely of `bearriver`'s `reactimate` if appropriate.
- Commit 2: Update `bearriver`'s changelog.

Please check out the recent history of this repository to see how we normally document commits, and how we link commits to issues in the subject line of the commit messages. Make sure you use `Refs <#issuenumber>` in the summary line, etc. I like being very regular and explicit with commit messages.

There was a similar issue with `embed` recently. The following two commits may help understand how to best document the changes and write the commit messages:

https://github.com/ivanperez-keera/dunai/commit/b23a4fe84840bd6f4038fd3769b78f441ab492fc
https://github.com/ivanperez-keera/dunai/commit/9210f04a8e31ff4ac7656ab0cad4bcd057a45ead

**Comment by solomon-b** [comment]
I'm trying to implement this with `morphS` and running into some trouble.

```
BR.reactimate senseI sense actuate (_ sf)
```

This hole is `SF a b -> BR.SF m a b`. So we need to write this:
```
    foldIdentity :: Monad m => SF a b -> BR.SF m a b
    foldIdentity = morphS $ pure . _ . MSF.runReader
```

But now I need `(DTime -> c) -> c` and have no obvious way to produce a `DTime`.

**Comment by ivanperez-keera** [comment]
I think the clue is:
```haskell
foldIdentity :: Monad m => SF a b -> BR.SF m a b
foldIdentity = morphS $ mapReaderT $ return . runIdentity
```

**Comment by ivanperez-keera** [comment]
Hi @solomon-b . Did you get a chance to try this idea?

**Comment by solomon-b** [comment]
Not yet, but I plan to work on it this weekend.

**Comment by ivanperez-keera** [comment]
Hi @solomon-b . Let me know if you want me to take a look at something, even if it's not complete. Thanks!

**Comment by solomon-b** [comment]
@ivanperez-keera I'm sorry for the delay. Work got really busy but I have time this weekend (for real this time). I'll get something together by end of day tomorrow.
