### ISSUE TITLE
Formulate functions in Control.Monad.Trans.MSF.* without the MSF constructor

### ISSUE THREAD

**Issue by turion** [ivanperez-keera/dunai#48]
We should always strive to formulate most functions without the MSF constructor in order to find out which parts really need the constructor and whether our API is complete. A user of the library should never need to use the constructor.

Most modules below Control.Monad.Trans.MSF don't satisfy this ideal.

This doesn't change the API, and (if done right) not even functionality.

**Comment by ivanperez-keera** [comment]
I would really like to get 0.2.1 out the door asap. Let's close documentation first, and then improve this for 0.2.2.

**Comment by ivanperez-keera** [comment]
(Modified the title. Originally said this should apply to other modules too.)

**Comment by turion** [comment]
If we're doing this for 0.2.2, we can do this for the whole library, not just `Control.Monad.Trans.MSF.*`.

**Comment by ivanperez-keera** [comment]
I suspect that might be quite hard (even just for these it might be hard).

**Comment by turion** [comment]
We might find places where we can't do it, and that's ok. I just want to isolate, classify and understand these places.

**Comment by turion** [comment]
At the moment, doing this forces me (on branch `develop_remove_MSF_constructor_wherever_possible`) to reorganise a lot of code (e.g. move things out of Core), so it has to go in 0.4.

**Comment by ivanperez-keera** [comment]
I wouldn't worry about slower in principle for now. There will be a time to address this systematically.

If you notice a leak, that's different.

**Comment by turion** [comment]
Ok. Removing the `MSF` constructor also reduces the number of places where we might have to look for a leak.
