### ISSUE TITLE
Document Data.VectorSpace.Fractional

### ISSUE THREAD

**Issue by ivanperez-keera** [ivanperez-keera/dunai#50]
This is a subticket of #32.

@turion Could you do this one?

**Comment by turion** [comment]
Yes, but we'd need to decide in #46 whether we want/need a `newtype` for this or not.

**Comment by ivanperez-keera** [comment]
That may be harder to do right. Let's address those issues separately. Besides: https://github.com/ivanperez-keera/dunai/issues/11
