### ISSUE TITLE
Cross-reference and code highlight documentation

### ISSUE THREAD

**Issue by turion** [ivanperez-keera/dunai#51]
We should add cross-references in the haddock, e.g. writing `'MSF'` in most places instead of `MSF` or `@MSF@`. Where no useful reference exist, still prefer monospace `@someHaskellConcept@` over someHaskellConcept.

**Comment by turion** [comment]
@ivanperez-keera is that alright with you? (Don't want to invest the effort if I don't know whether the PR would be accepted)

**Comment by ivanperez-keera** [comment]
Sure.
