### ISSUE TITLE
Create reverse frp zoo

### ISSUE THREAD

**Issue by ivanperez-keera** [ivanperez-keera/dunai#52]
It could live in examples, as an independent directory, with one cabal file with multiple applications/demos, and one or several markdown files explaining what each example is about.

**Comment by turion** [comment]
Ideally it would run or benchmark the dunai version against the native version. That would suggest giving each framework a separate cabal file to minimise dependencies.

**Comment by ivanperez-keera** [comment]
I've done this with a flag in the past.
