### ISSUE TITLE
Import all instances from Data.MonadicStreamFunction.Instances.*, or avoid orphan instances

### ISSUE THREAD

**Issue by turion** [ivanperez-keera/dunai#55]
Currently we have orphan instances in several modules `Data.MonadicStreamFunction.Instances.*`. Some of them (`ArrowChoice`, `ArrowLoop`, `ArrowPlus`) are imported in `Data.MonadicStreamFunction` (the module usually imported by users) and some others (`Num`, `VectorSpace` etc.) are not. This creates a few problems:

1. The haddock documentation does not display any instances for `MSF` in the place where it's defined (`Data.MonadicStreamFunction.Core`), or in `Data.MonadicStreamFunction`. The user would have to visit the submodule `Data.MonadicStreamFunction.Instances.*` in order to even find out about it.
2. The user doesn't have the instances `Num` etc. until they explicitly import the corresponding submodule.
3. Orphan instances are generally frowned upon (although they probably won't do any harm here).

Problem 2. would be solved by importing all instances from all submodules `Data.MonadicStreamFunction.*`.
Problem 1. might be solved by somehow explicitly reexporting the name `MSF` in `Data.MonadicStreamFunction`, but I don't know haddock well enough. Right now it is halfway solved by explicit documentation in `Data.MonadicStreamFunction`.

The solution to all those problems, that a vanilla haskell package maintainer might bring forward is just to avoid orphan instances by putting all instances into `Data.MonadicStreamFunction.Core`, directly where `MSF` is defined. There is no real downside to it, except that the file gets a little longer.

**Comment by ivanperez-keera** [comment]
Obviously, this would mean you do not get to implement your own instances as a dunai user.

I think this is going to be a problem for some `Arrow*` stuff, but it's merely an intuition based on issues we had in Yampa with multiple possible instance definitions. I cannot be sure until I try more things, which is not going to happen soon.

An example of how this has been addressed in `Data.VectorSpace.Specific`:

```haskell
-- | Vector space instances for concrete/specific types.
--
-- This module contains:
--
--     * 'RModule' instances for 'Int', 'Integer', 'Double' and 'Float'.
--
--     * 'VectorSpace' for 'Double' and 'Float'.
```

The main module could list the instances contained in submodules in the documentation.

**Comment by turion** [comment]
Any new insights? I still think we should get rid of the orphan instances. Dunai users wanting new instances should use `newtype`s, which are easy to handle with `newtype-generics` (and similar packages).

**Comment by ivanperez-keera** [comment]
> Any new insights?

None so far. I live reasonably ok with orphan instances for now. I'd rather make this decision conservatively.

I still think adding them is going to be a problem down the line, so nothing is going to be done in this line for now.

> which are easy to handle with newtype-generics (and similar packages).

I'm not sure how easy they are to handle, or the implications of using that in practice.

Maybe this decision can be revisited in the future, but for now they are not going to be merged into the main module.
