### ISSUE TITLE
Test examples with travis

### ISSUE THREAD

**Issue by turion** [ivanperez-keera/dunai#58]
We should build all the examples with travis as well. As inspiration for a `.travis.yml` that works for several cabal packages in the same repository, have a look [here](https://github.com/turion/rhine/blob/dev_rhine_gloss/.travis.yml).

**Comment by ivanperez-keera** [comment]
You may have changed things. Do you mean the current? https://github.com/turion/rhine/blob/master/.travis.yml

Thanks for providing that file. This is useful. Is this possibility of compiling multiple packages by changing PACKAGE in the environment in the build matrix documented anywhere in Travis' documentation?

And a question I'm pondering: should bearriver compile against the version of dunai in the repo or the one on hackage? And what does it mean in each case? And how to do that with the generality you use in that travis file? (`for i in $(find ../ -iname '*.cabal' | xargs -n 1 dirname); do cabal sandbox add-source $i; done` ?)

**Comment by turion** [comment]
This feature is documented since a few days (I added it :grin:) in https://docs.travis-ci.com/user/languages/haskell/#Build-Matrix. It might mean that `dunai` needs to go to a subdir as well.

I think `bearriver` should compile against the hackage version, because the typical use case is that people will create a new project and just put `bearriver` and `dunai` in the dependencies, which gets them from hackage. Coincidentally, this also simplifies the build process, since we don't need to use `cabal sandbox add-source`.

**Comment by ivanperez-keera** [comment]
Agreed.

**Comment by turion** [comment]
So can we add the other example packages to the travis build as well now?

**Comment by ivanperez-keera** [comment]
Yes.

We can add those that we are ready to make a compromise to maintain.

The travis file should not push those to hackage, though. This needs to be adjusted in the deploy condition.

**Comment by turion** [comment]
IMHO, we should maintain all examples, or remove them from the repo.

**Comment by turion** [comment]
Any opinion about how to proceed with version numbers in the examples? Two possibilities come to my mind:

* Treat all example packages individually, i.e. let each one have its own version numbers
* Bump version numbers synchronously with dunai (I do that with rhine and its subsidiary packages)

**Comment by ivanperez-keera** [comment]
> Any opinion about how to proceed with version numbers in the examples? Two possibilities come to my mind:
> 
>     Treat all example packages individually, i.e. let each one have its own version numbers
>
>     Bump version numbers synchronously with dunai (I do that with rhine and its subsidiary packages)

For examples that go with the library, this is nice because it gives some consistency. But it's not possible, e.g. with haskanoid, because it also needs to sync with the main project.

It's an idea we should consider in the future, when we collect a more comprehensive set of examples that accompany dunai in the form of some coherent, well-structured tutorial.
