### ISSUE TITLE
Publish dunai - 0.4

### ISSUE THREAD

**Issue by ivanperez-keera** [ivanperez-keera/dunai#62]
In order for bearriver to compile directly from hackage, it needs features that are not in the current version of dunai. So, we need to publish also dunai as is, and include new changes in the future.

I believe this would have to be 0.4, if there were changes to the API (moves, deletions) since 0.3. I'd be happy to be proven wrong.

List of changes:

        * Adds support for random numbers using MonadRandom
          (thanks Jonathan Thaler -- @thalerjonathan).
        * Removes MSF constructor from many definitions
          (by Manuel Bärenz -- @turion).
        * Adds support for older GHC versions.
        * Moves some definitions/modules around.
        * dunai.cabal: Version bump (0.4).
        * examples/: Changes licenses, updates examples to use new API.

**Comment by ivanperez-keera** [comment]
@turion Opinions? Anything missing?

**Comment by turion** [comment]
It's definitely 0.4 I'm afraid, since I moved a few definitions.

We don't have a v0.3.0.0 tag, so it's a bit hard to see the diffs.

**Comment by ivanperez-keera** [comment]
I've just set the tag to the version that was released.

**Comment by ivanperez-keera** [comment]
Done.
