### ISSUE TITLE
Formulate more functions without the `MSF` constructor

### ISSUE THREAD

**Issue by turion** [ivanperez-keera/dunai#69]
#48 in hindsight was only about removing `MSF` from functions in `Control.Monad.Trans.MSF.*`, and also there not from every function, especially the lifting functions. This issue is about coordinating and overviewing the different efforts in this direction.

# Advantages

* Clearer overview what the essential building blocks are
* Fewer places where one would have to optimise (strictness etc.)
* Fewer places where one would have to change code if we were to change the core implementation (e.g. adopting insights from causal commutative arrows and stream fusion).

# Places where we could remove `MSF` ...

## ...safely

* `switch`: In terms of exceptions. (Depends on #53)
* Most lifting functions in `Control/Monad/Trans/MSF`: In terms of generalised lifting (#16).
 
## ...quite possibly with performance penalties or inconveniences

* `Core`
 * `delay`/`iPre`: In terms of `feedback`.
 * `reactimate`: In terms of `embed`.

# Places where I have no idea how to remove it

* `Control/Monad/Trans/MSF/Except.hs`: `Monad MSFExcept` instance, and `exceptS` (Exception catching is not ordinary lifting, it seems...)
* `Data/MonadicStreamFunction/Parallel.hs`

**Comment by ivanperez-keera** [comment]
Thanks @turion for exploring what could be simplified.

I'm happy with the changes in `switch`, `Control/Monad/Trans/MSF`, `Core`, `delay`, `iPre`. This would give us a quite minimal core already.

I'd suggest delaying changes to `reactimate`, and "Places where I have no idea how to remove it" for now.

**Comment by turion** [comment]
And speaking of `delay` and `iPre`. Should we remove `delay` completely? (I personally like the word much more than `iPre`.)

**Comment by turion** [comment]
Reviewing #16 shows that there is no good solution right now to rid all lifting functions from the `MSF` constructor. I'd therefore exempt them from this issue for now.

To resolve `switch` in terms of exceptions, I'm going to move it out of 'Core`, which solves part of #53.

**Comment by turion** [comment]
Reorganising the modules so that importing exceptions in `Data.MonadicStreamFunction.Util` does not form an import cycle touches so many aspects of #53 that we really need a decision there first.

**Comment by ivanperez-keera** [comment]
This issue is a bit open ended. It'll be approached in a different way as the class for reactive construct is introduced in upcoming work.
