### ISSUE TITLE
Cleanup Control.Arrow.Util, remove >-> and <-<, 

### ISSUE THREAD

**Issue by turion** [ivanperez-keera/dunai#71]
There are a few things in Control.Arrow.Util that don't seem to be used much. In particular, as @ggreif identified in [this issue](https://github.com/turion/rhine/issues/16), the operators `>->` and `<-<` (defined [here](https://github.com/ivanperez-keera/dunai/blob/39407d26f2535b4550d8f02907045cca5c1a2e5c/src/Control/Arrow/Util.hs#L11)) are leftovers from old experiments that have been ported to rhine.

I propose:

* Delete `>->` and `<-<`.
* Let's decide what other functions in this module we need, and how we make them more prominent (e.g. using them in code, documenting them), or else delete them.

**Comment by ivanperez-keera** [comment]
For now, I'm happy with these two functions going away. @ggreif or @thalerjonathan if you want a "free" accepted PR, go for it :)

I wouldn't mind cleaning this module at some point, but we currently have 17 open (mostly) non-trivial issues. There's only so many things we can pay attention to.
