### ISSUE TITLE
Bearriver does not compile with GHC 7.6

### ISSUE THREAD

**Issue by ivanperez-keera** [ivanperez-keera/dunai#74]
I'm not sure we still want to support GHC 7.6, but bearriver does not currently compile with GHC 7.6 simply because the constraint on base is `>=4.7`, not `>=4.6`.

Just to be consistent with the current `.travis.yml` file, we could support GHC 7.6.

This merely requires changing the lower boundary in bearriver's cabal file.

**Comment by ivanperez-keera** [comment]
I suggest we keep it around for as long as it lasts, but don't make much of an effort to be backwards compatible with 7.6. I would prefer to support 7.8 for now.

I'm not sure how to make a sensible decision about how far back to go. The lowest I'm using for Android right now is 7.10, although I have some 7.8 apps lying around.

**Comment by turion** [comment]
Sounds good to me. Just support a particular version until it would become an effort to support it, at which point it can be dropped. We could add a line in the README or elsewhere to mention the oldest GHC version that is still supported.

**Comment by ivanperez-keera** [comment]
Sounds good to me to have that line upfront so that users know what to expect.

**Comment by ivanperez-keera** [comment]
Actually, until recently I was using a version of GHC without the Functor-Monad hierarchy and dunai wouldn't compile for me unless I changed that by hand.
