### ISSUE TITLE
Orphan instances in Data.VectorSpace.*

### ISSUE THREAD

**Issue by turion** [ivanperez-keera/dunai#76]
We still have orphan instances in `Data.VectorSpace.*`. They can sometimes give really strange error messages. E.g. importing `Data.VectorSpace.Tuples ()` but not `Data.VectorSpace.Primitive ()` will give confusing error messages when trying to evaluate `(1, 2) ^* 3`. (I just wasted some time with this...)

As discussed in #46, we could do the following:

* Change the `instance Fractional a => VectorSpace a` from `Data.VectorSpace.Fractional` to a `newtype`-style instance. 
* Put all `VectorSpace` instances into `Data.VectorSpace` and have no orphan instances.

**Comment by turion** [comment]
If you're ok with this, I'll send a PR.

**Comment by turion** [comment]
@ivanperez-keera, your opinion on this?

**Comment by ivanperez-keera** [comment]
What's the answer to the following (from #46):

> 
> > > Then Data.VectorSpace.Fractional wouldn't compile I think because it would overlap with the instances from Data.VectorSpace. (But we could still newtype them.)
> > 
> > I just tried to move everything in Specific into VectorSpace and the library does compile. What I don't know is if GHC will be confused when choosing instances for some types if some modules are imported.
> > 
> Ah maybe that's the problem then. If it ever occurs, let's just create a newtype FractionalVectorSpace.

If you do not foresee that any instance might need to be re-implemented differently, then sure, put all the instances in `Data.VectorSpace` and send a PR. If you can find a test/case where the `newtype` would be required, then think a bit more about how to best structure this.

**Comment by ivanperez-keera** [comment]
Are you ok with me assigning this to you?
