### ISSUE TITLE
`dunai`: Use an external 'void'

### ISSUE THREAD

**Issue by turion** [ivanperez-keera/dunai#79]
In `Control.Monad.Trans.MSF.Except`, we use our own `Empty` type. We could use the [`void`](http://hackage.haskell.org/package/void) package instead. This would make the concept simpler to grasp for Haskell users that already know `void`.

The only downside is another dependency, and the dependencies that `void` brings: `deepseq`, `ghc-prim`, `hashable` and `semigroups`.

**Comment by ivanperez-keera** [comment]
I'm ok accepting this so long as it does not actually run Template Haskell during compilation (see [tagged](http://hackage.haskell.org/package/tagged)).

**Comment by turion** [comment]
We can't guarantee that it will in some future release. And I don't want to look through the `tagged` code and guess whether it will.

Instead, I heart-brokenly propose to just rename `Empty` to `Void`. (Or if you think this is not an important issue, we can just close it as `wontfix`.)

**Comment by turion** [comment]
Following the discussion in #13, we should wait until GHC 7.8 can be deprecated and then use the `void` package.

**Comment by turion** [comment]
`Void` is part of base as of GHC 7.10. So once we have deprecated 7.8 we don't even need that external dependency.

**Comment by ivanperez-keera** [comment]
The need to avoid `template-haskell` is only applicable to GHC versions higher than 8.0 at this point.

Since the dependency on `void` is only applicable to versions of GHC in the 7 series, I am happy accepting this and getting rid of `Empty`.
