### ISSUE TITLE
Finish Control.Monad.Trans.MSF.RWS

### ISSUE THREAD

**Issue by turion** [ivanperez-keera/dunai#81]
The module `Control.Monad.Trans.MSF.RWS` exists in the repo but is not listed in the `.cabal` file. It can be finished quickly using generic lifting functions, I think.

**Comment by turion** [comment]
I mistyped the commit message in the above commit, issue is still open.

**Comment by ivanperez-keera** [comment]
Do you want me to merge this then, or wait for a future PR?

**Comment by turion** [comment]
It's fixed now, can be merged.

**Comment by ivanperez-keera** [comment]
Thanks.
