### ISSUE TITLE
Strict vs. Lazy State

### ISSUE THREAD

**Issue by thalerjonathan** [ivanperez-keera/dunai#85]
Dunai has built the stateS implementation on the strict implementation of StateT of mtl, so one should always import Control.Monad.State.Strict because when importing Control.Monad.State one runs into type errors because the latter one imports the lazy State.

So I guess in general I should always import Control.Monad.State.Strict when I want to use your stateS somewhere in my library?

**Comment by turion** [comment]
I think the best solution would be to completely reexport the `StateT` module we're using. We're not using `mtl`, we're using `transformers`. We could add `mtl` as a dependency, shouldn't matter.

**Comment by thalerjonathan** [comment]
Ok thanks for the info. What is the difference between ``mtl`` and ``transformer`` ?

**Comment by turion** [comment]
Ah :) a good question, and an important one. First of all: `mtl` is based on `transformers` and reexports a lot of modules from there.

# `transformers`...

* defines monad transformers like `StateT`
* gives functions like `stateT :: Monad m => (s -> (a, s)) -> StateT s m a` and `runStateT :: StateT s m a -> s -> m (a, s)` to add or remove transformer layers from the _top_ of your stack
* gives functions like `get :: Monad m => StateT s m s` to access/use the transformer layer on the _top_ of your stack

Its only drawback is that it's hard to access transformer layers that are not on the top of your stack. (You have to use a lot of `lift`s.)

# `mtl`...

* gives functions like `get :: MonadState s m => m s` that allow you to access a state side effect in a more general setting, e.g. anywhere in your transformer stack.

## How?

* The `class MonadState s m` basically says "`m` has the capability of storing and retrieving a state variable of type `s`".
* Obviously, there is an `instance MonadState s (StateT s m)`, meaning that if you add a `StateT` on the top of your stack, you have the capability to store and retrieve state, by accessing `transformers`' functions.
* But there is also an instance `(MonadState s m, MonadTrans t) => MonadState s (t m)`, meaning that if your monad `m` already has the capability of manipulating state, you can add an arbitrary monad transformer layer on top of that, and you will still be able to access that state! That's something that `transformers` can't do well.
* Finally, if you have a monad that is capable of manipulating state, but you don't want to implement it as a transformer stack including `StateT`, you could just implement an instance for `MonadState`, giving you a good api.

# When do I need what?

Sometimes, you'll need both. They work well with each other.

* If you need to manipulate the transformer layers by removing or adding some, you need `transformers`.
* If your transformer stack is not big, you might not need `mtl`.
* If your transformer stack is big, and/or you need to access transformers from arbitrary positions in the stack, use `mtl`.

**Comment by turion** [comment]
@ivanperez-keera , any particular feelings about including `mtl` in the dependencies (it's already an indirect dependency) and reexporting the respective modules (e.g. `Control.Monad.State` from `Control.Monad.Trans.MSF.State`)?

**Comment by ivanperez-keera** [comment]
> @ivanperez-keera , any particular feelings about including mtl in the dependencies (it's already an indirect dependency) and reexporting the respective modules (e.g. Control.Monad.State from Control.Monad.Trans.MSF.State)?

If there's an expectation that people will almost always need to use `Control.Monad.State` when they use `Control.Monad.Trans.MSF.State`, then I think that's acceptable.

**Comment by turion** [comment]
There is a downside: If people want to use `monads-tf`, which is essentially like `mtl`, but with functional dependencies replaced by type families (i.m.o much nicer conceptually), they wouldn't be able to, because type class names and module names clash with `mtl`. So by reexporting stuff from `mtl`, we restrict people not to use `monads-tf`. So maybe it's better to solve the problem by improving the documentation?
