### ISSUE TITLE
Can't implement this "MSF pool" function in terms of ListT or exceptions

### ISSUE THREAD

**Issue by turion** [ivanperez-keera/dunai#86]
I have the following function (taken from [here](https://github.com/turion/rhine-tutorial/blob/ea19125e22dfc35ccbd3a7c40002c095e306d0f0/Util.hs#L7)), which I cannot implement without the `MSF` constructor (#69):

```haskell
-- | Accumulates inputs and starts an MSF for each of them
pool :: Monad m => (a -> MSF m () b) -> MSF m [a] [b]
pool f = pool' f []
  where
    pool' :: Monad m => (a -> MSF m () b) -> [MSF m () b] -> MSF m [a] [b]
    pool' f msfs = MSF $ \as -> do
      let moremsfs = msfs ++ map f as
      (bs, msfs') <- unzip <$> sequence (map (flip unMSF ()) moremsfs)
return (bs, pool' f msfs')
```
The idea is straightforward: I have a "starting function" that starts an `MSF` for a value of type `a`. I run all of these `MSF`s in parallel and collect their output in a list.

I have the suspicion that the fundamental primitive for this is the dreaded monad instance for `MSF`s, i.e. `join :: MSF m a (MSF m a b) -> MSF m a b`, or `(>>=) :: MSF m z a -> (a -> MSF m z b) -> MSF m z b`.

**Comment by turion** [comment]
I've tried (unsuccesfully) to implement `pool` in terms of `MSF (ListT m) a b`, but this didn't work.

**Comment by turion** [comment]
Possibly, I need something like `appendS :: MSF m a (MSF (ListT m) a b) -> MSF (ListT m) a b` (building upon #89) that appends all `MSF`s.

**Comment by turion** [comment]
A related and maybe simpler to define function would be `MSF m a (MSF (MaybeT m) a b) -> MSF m a b` which executes an `MSF (MaybeT m) a b` until it terminates, and then switches to the next one. This should be implementable in terms of exceptions, it's nearly the `join` of the `MSFExcept` monad.

**Comment by ivanperez-keera** [comment]
Closed due to inactivity and having no clear path to proceed.
