### ISSUE TITLE
Allow generic deriving of vector spaces

### ISSUE THREAD

**Issue by turion** [ivanperez-keera/dunai#92]
This is for the future, or might possibly become obsolete when we use an external vector space package.

A user might define their own vector type:

```haskell
data MyVector = MyVector
  { x :: Double
  , y :: Double
  }
```
It's tedious having to define `VectorSpace` instances for each of them manually, and can be done with `Generic`s.

**Comment by ivanperez-keera** [comment]
I don't think we should make this a central point, or that we should deal with it.

If it becomes an issue, then maybe it's a sign that vectorspace belongs separately or we should use a different library. That way maybe Yampa could also use it.

I am closing this. We can reopen it if you want to actively start working on it for a _next_ release.
