### ISSUE TITLE
Reorg: function naming: no input

### ISSUE THREAD

**Issue by ivanperez-keera** [ivanperez-keera/dunai#99]
In #26 a new renaming policy was discussed. One of the choices we did not agree on was how to name functions to _deal with something with no input_.

For example:
```
arrM_ :: m b -> MSF m a b
```
as opposed to

```
arrM :: (a -> m b) -> MSF m a b
```

We start from @turion 's initial suggestion:

> Suffix _ specialises to something not having an input. Example: arrM_ :: m b -> MSF m a b

This issue is here so that we can discuss that particular naming choice, and that one _only_.

Please, try to make the decision simple and local, minimize the information to handle to make a decision, and avoid making this issue depend on other issues (or the other way around).

I will copy the parts of the other discussion that seem relevant here, citing the original commenter and source.

**Comment by ivanperez-keera** [comment]
> In https://github.com/ivanperez-keera/dunai/issues/26#issuecomment-335034732, @ivanperez-keera said:
> 
> My intuition is that if something ends in _, the type is h () for some h (probably an MSF m a ()). For instance, I'd call arrM_ constM or constantM.

**Comment by ivanperez-keera** [comment]
In https://github.com/ivanperez-keera/dunai/issues/26#issuecomment-335036058, @turion said:

>     My intuition is that if something ends in _, the type is h () for some h (probably an MSF m a ()).
> 
> Ah yes, you're right.
> 
>     For instance, I'd call arrM_ constM.
> 
> Or rather constArrM or arrMConst?

**Comment by ivanperez-keera** [comment]
In https://github.com/ivanperez-keera/dunai/issues/26#issuecomment-341663213, @turion said:

> **const**
> 
> > My intuition is that if something ends in _, the type is h () for some h (probably an MSF m a ()). For instance, I'd call arrM_ constM or constantM.
> 
> I like constM, and yes, you're absolutely right about _.

**Comment by ivanperez-keera** [comment]
In https://github.com/ivanperez-keera/dunai/issues/26#issuecomment-350369844, @turion said:

> The suffix _ was used in Control.Monad.Trans.MSF.Reader and other places to distinguish e.g. runReaderS_ :: Monad m => MSF (ReaderT s m) a b -> s -> MSF m a b from runReaderS :: Monad m => MSF (ReaderT s m) a b -> MSF m (s, a) b, i.e. function argument vs. MSF live input. I suggest we keep that convention and apply it to Control.Monad.Trans.MSF.Random.

**Comment by ivanperez-keera** [comment]
It seems like, for small functions like `arrM`, we did agree on switching to the prefix `const`.

However, what you seem to be suggesting now (3 months ago) is that we do not.

Do you mean that generally `_` would mean 'no input' or 'no output'?

Is there a different naming policy that affects `runReaderS_` and would suggest a different name for it?

**Comment by turion** [comment]
I don't feel very strongly about either `_` or `const`.

* You made a good point that the suffix `_` says that output is discarded, and I think we should stick to this.
* I really like `constM :: m a -> MSF m arbitrary a` (and `constS :: a -> MSF m arbitrary a`).
* I don't have any good ideas for `runReaderS_` and the other similar running functions, but I think we could leave it with the `_` although it doesn't discard output (some other libraries are quite liberal with the `_` suffix, I think). But pick whatever you feel good about there.

**Comment by ivanperez-keera** [comment]
> I really like constM :: m a -> MSF m arbitrary a (and constS :: a -> MSF m arbitrary a).

I also like your constS.

> I don't have any good ideas for runReaderS_ and the other similar running functions, but I think we could leave it with the _ although it doesn't discard output (some other libraries are quite liberal with the _ suffix, I think). But pick whatever you feel good about there.

I don't mind having a temporary name in the hope we'll find a better one. So, once again, the decision is not at all fixed in stone.

This construction has to do with commuting the transformer, possibly only for containers. I think time will help us come up with a better naming scheme.

Suffixes in Haskell are mostly taken. A quick search through the library reveals only one top-level function with  the suffix ' (apostrophe), `throwOn'`, which is precisely a _"[v]ariant of 'throwOn', where the exception may change every tick"_. The difference is that it's built "the other way", meaning that the one with the prime is the one in which the input stream of the MSF is affected. (I'm not saying prime is better than _, but at least we will not be overlapping naming policies, and later we can just change all apostrophes to `<whatever>`.)

Would a policy like the following make sense?

- Without prime, it is the standard running/lifting/morphing/hoisting function, with the arguments out.
- With prime, it means the inputs and the outputs of the MSF are affected instead.

For example:
```
runReaderS :: Monad m => MSF (ReaderT s m) a b -> s -> MSF m a b from
runReaderS' :: Monad m => MSF (ReaderT s m) a b -> MSF m (s, a) b

throwOn :: Monad m => e -> MSF (ExceptT e m) Bool ()
throwOn' :: Monad m => MSF (ExceptT e m) (Bool, e) ()
```

I suspect some combinations may not exist or make sense (possibly when they mess with the outputs). For example, we may have a `blabla'`, but not a `blabla`.

I don't feel very strongly about which should be which, so I'm happy swapping them here (meaning that `runReaderS/runReaderS'` remain as is, and we swap the names of `throwOn/throwOn'`.)

Is it going to bite us anywhere?

**Comment by ivanperez-keera** [comment]
(Of course, prime might be a terrible choice, which is why we went for underscore in the past. So, if it's plainly annoying, also say that :) )

**Comment by turion** [comment]
Your prime policy makes sense. We would see in a PR whether there is a problem anywhere.
